// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// Import the asm.js version of the Cardano Serialization Library
import * as CardanoWasm from '@emurgo/cardano-serialization-lib-asmjs';
// END EXTRA CODE

/**
 * @param {string} walletIdentifier
 * @returns {Promise.<string>}
 */
export async function JavaScript_action(walletIdentifier) {
	// BEGIN USER CODE
    try {
        // Check for wallet availability
        if (!window.cardano || !window.cardano[walletIdentifier]) {
            throw new Error('CIP-30 compatible wallet (e.g., ' + walletIdentifier + ') is not available.');
        }

        // Enable the wallet
        const walletApi = await window.cardano[walletIdentifier].enable();

        // Get the user's addresses
        const addressesHex = await walletApi.getUsedAddresses();
        if (!addressesHex || addressesHex.length === 0) {
            throw new Error('No addresses found in the wallet.');
        }

        // Convert the first address from hex to Address object
        const userAddress = CardanoWasm.Address.from_bytes();
		if (!userAddress || userAddress.length === 0) {
			throw new Error('No addresses found in the wallet.');
		}
        // TODO: Replace the hardcoded protocol parameters with dynamic fetching from Blockfrost or another API
        const protocolParams = {
            minFeeA: '44',
            minFeeB: '155381',
            poolDeposit: '500000000',
            keyDeposit: '2000000',
            coinsPerUtxoByte: '34482', // Use '4310' for Mainnet
            maxTxSize: 16384,
            maxValueSize: 5000,
        };

        // Initialize the LinearFee object
        const linearFee = CardanoWasm.LinearFee.new(
            CardanoWasm.BigNum.from_str(protocolParams.minFeeA),
            CardanoWasm.BigNum.from_str(protocolParams.minFeeB)
        );

        // Build the Transaction Builder Configuration
        const txBuilderCfg = CardanoWasm.TransactionBuilderConfigBuilder.new()
            .fee_algo(linearFee)
            .pool_deposit(CardanoWasm.BigNum.from_str(protocolParams.poolDeposit))
            .key_deposit(CardanoWasm.BigNum.from_str(protocolParams.keyDeposit))
            .coins_per_utxo_byte(CardanoWasm.BigNum.from_str(protocolParams.coinsPerUtxoByte))
            .max_value_size(protocolParams.maxValueSize)
            .max_tx_size(protocolParams.maxTxSize)
            .build();

        // Initialize the Transaction Builder
        const txBuilder = CardanoWasm.TransactionBuilder.new(txBuilderCfg);

        const recipientAddress = CardanoWasm.Address.from_bech32('addr_test1qpyfdeatl0t9mz59lfmqgyju29q4fxxe2xs429padumkt2dh48uucv55pm2ylr4ysxphxurn4aycqw72euejp3ywwr4qlf9g04'); // Replace with actual address

		// 1. Add inputs
		// 2. Add outputs
		// 3. Add time to live
		// 4. set fee


        // Create the output (sending 2 ADA to the recipient)
        const amount = CardanoWasm.Value.new(CardanoWasm.BigNum.from_str('2000000')); // 2 ADA in lovelace
        const output = CardanoWasm.TransactionOutput.new(recipientAddress, amount);

        // Add the output to the transaction
        txBuilder.add_output(output);

        // Fetch the user's UTXOs
        const utxosHex = await walletApi.getUtxos();
        if (!utxosHex || utxosHex.length === 0) {
            throw new Error('No UTXOs found in the wallet.');
        }

        // Convert UTXOs from hex to TransactionUnspentOutput objects
        const utxos = utxosHex.map((utxoHex) =>
            CardanoWasm.TransactionUnspentOutput.from_bytes(
                CardanoWasm.Util.hex_to_bytes(utxoHex)
            )
        );

        // Add inputs to the transaction
        for (const utxo of utxos) {
            txBuilder.add_input(
                utxo.output().address(),
                utxo.input(),
                utxo.output().amount()
            );
        }

        // Set the change address and calculate fees
        txBuilder.add_change_if_needed(userAddress);

        // Build the transaction body
        const txBody = txBuilder.build();

        // Convert the transaction body to hex
        const txBodyHex = CardanoWasm.Util.bytes_to_hex(txBody.to_bytes());

        // Sign the transaction using the wallet
        const witnessesHex = await walletApi.signTx(txBodyHex);

        // Convert witnesses from hex to TransactionWitnessSet
        const witnesses = CardanoWasm.TransactionWitnessSet.from_bytes(
            CardanoWasm.Util.hex_to_bytes(witnessesHex)
        );

        // Assemble the signed transaction
        const signedTx = CardanoWasm.Transaction.new(txBody, witnesses);

        // Convert the signed transaction to hex
        const signedTxHex = CardanoWasm.Util.bytes_to_hex(signedTx.to_bytes());

        // Submit the transaction via the wallet
        const txHash = await walletApi.submitTx(signedTxHex);

        // Return the transaction hash
        return txHash;
    } catch (error) {
        // Handle errors
        console.error('Transaction failed:', error);
        throw error;
    }
	// END USER CODE
}
