// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<MxObject[]>}
 */
export async function JS_ListAvailableWallets() {
	// BEGIN USER CODE
	if (typeof window.cardano !== 'undefined') {
        const wallets = Object.keys(window.cardano).filter(wallet => window.cardano[wallet].enable);
        const walletDetails = wallets.map(wallet => ({
            name: window.cardano[wallet].name,
            icon: window.cardano[wallet].icon,
            identifier: wallet
        }));

        const mxObjects = [];
        const walletEntity = "CardanoLightWallet.Wallet";

        for (const wallet of walletDetails) {
            const mxObject = await new Promise((resolve, reject) => {
                mx.data.create({
                    entity: walletEntity,
                    callback: resolve,
                    error: reject
                });
            });
            mxObject.set("Name", wallet.name);
            mxObject.set("Icon", wallet.icon);
            mxObject.set("WalletID", wallet.identifier);
            mxObjects.push(mxObject);
        }

        return mxObjects;
    } else {
        throw new Error('No Cardano wallets found');
    }
	// END USER CODE
}
