// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function JS_GetCardanoWalletRewardAddresses() {
	// BEGIN USER CODE
	// This action retrieves the stake (reward) address from the Cardano wallet

    try {
        // Ensure the Cardano wallet is enabled
        const wallet = await window.cardano.enable();

        // Get the reward addresses associated with the wallet
        const rewardAddresses = await wallet.getRewardAddresses();

        // Typically, you want the first reward address
        const stakeAddress = rewardAddresses[0];

        // Return the stake address as the output of this action
        return stakeAddress;

    } catch (error) {
        // Handle any errors that occur during the process
        console.error("Error retrieving the Cardano wallet stake address:", error);
        return null;
    }
	// END USER CODE
}
