// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} wallet
 * @param {string} transactionData - CBOR-encoded transaction data
 * @returns {Promise.<string>}
 */
export async function JS_SignCardanoWalletTransaction(wallet, transactionData) {
	// BEGIN USER CODE
    const walletIdentifier = wallet.get('_id');
    if (!cardano || !cardano[walletIdentifier]) {
        console.error('Wallet not found');
        return false;
    }

    try {
        // Re-enable the wallet and retrieve the wallet API object
        const cardanoWallet = await cardano[walletIdentifier].enable();
        if (!cardanoWallet) {
            throw new Error('Could not enable wallet');
        }

        console.info('Cardano Wallet enabled:', cardanoWallet);

        // Sign the transaction with the wallet
        const signedTransaction = await cardanoWallet.signTx(transactionData, false);

        return signedTransaction;
    } catch (error) {
        console.error("Error signing the transaction:", error);
        return null;
    }
	// END USER CODE
}
