// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} walletIdentifier
 * @param {string} transactionData - CBOR-encoded transaction data
 * @returns {Promise.<string>}
 */
export async function JS_SignAndSubmitCardanoWalletTransaction(walletIdentifier, transactionData) {
	// BEGIN USER CODE
    try {
		const cardanoWallet = await window.cardano[walletIdentifier].enable();

        // Sign the transaction with the wallet
        const signedTransaction = await cardanoWallet.signTx(transactionData, false);
        const txHash = await cardanoWallet.submitTx(signedTransaction);

        return signedTransaction;
    } catch (error) {
        console.error("Error signing the transaction:", error);
        return null;
    }
	// END USER CODE
}
