// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} wallet
 * @returns {Promise.<boolean>}
 */
export async function JS_Wallet_Connect(wallet) {
	// BEGIN USER CODE
    const walletIdentifier = wallet.get('_id');
    if (window.cardano && window.cardano[walletIdentifier]) {
        try {
            const cardanoWallet = await window.cardano[walletIdentifier].enable();

            const networkId = await cardanoWallet.getNetworkId();

            // Update the RewardAddress attribute of the Wallet object
            wallet.set('NetworkID', networkId);

            // Get the reward addresses associated with the wallet
            const rewardAddresses = await cardanoWallet.getRewardAddresses();

            // Typically, you want the first reward address
            const stakeAddress = rewardAddresses[0];
            console.log(stakeAddress);
            
            // Update the RewardAddress attribute of the Wallet object
            wallet.set('RewardAddress', stakeAddress);

            return true; // Indicate success
        } catch (error) {
            console.error('Failed to connect wallet:', error);
            throw new Error('Wallet connection failed');
        }
    } else {
        throw new Error('Wallet not found');
    }
	// END USER CODE
}
