// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import * as CardanoWasm from '@emurgo/cardano-serialization-lib-asmjs';
// END EXTRA CODE

/**
 * @param {MxObject} wallet
 * @returns {Promise.<string>}
 */
export async function JS_Wallet_Connect2(wallet) {
	// BEGIN USER CODE
	//const walletIdentifier = 'eternl';
	const hexToBytes = (hex) => {
		const bytes = new Uint8Array(hex.length / 2);
		for (let i = 0; i < hex.length; i += 2) {
		bytes[i / 2] = parseInt(hex.substr(i, 2), 16);
		}
		return bytes;
	};	

	try {
		const walletIdentifier = wallet.get('_id');
		if (!cardano || !cardano[walletIdentifier]) {
			console.error('Wallet not found');
			return false;
		}
		const cardanoWallet = await cardano[walletIdentifier].enable();
		
		const networkId = await cardanoWallet.getNetworkId();
		wallet.set('NetworkID', networkId);

		const usedAddresses = await cardanoWallet.getUsedAddresses();
		if (usedAddresses) {
			const baseAddressHex = usedAddresses[0];
		    const baseAddressBytes = CardanoWasm.Address.from_bytes(hexToBytes(baseAddressHex));
			const baseAddress = baseAddressBytes.to_bech32();
			wallet.set('BaseAddress', baseAddress);
		}
		
		return usedAddresses[0];
	} catch (error) {
		return '';
	}
//	return networkId;
	// END USER CODE
}
