// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} wallet
 * @returns {Promise.<boolean>}
 */
export async function JS_Wallet_Connect(wallet) {
	// BEGIN USER CODE
    const walletIdentifier = wallet.get('_id');
    if (!cardano || !cardano[walletIdentifier]) {
        console.error('Wallet not found');
        return false;
    }

    try {
        // Re-enable the wallet and retrieve the wallet API object
        const cardanoWallet = await cardano[walletIdentifier].enable();
        if (!cardanoWallet) {
            throw new Error('Could not enable wallet');
        }

        console.log('Cardano Wallet enabled:', cardanoWallet);

        // Get the network ID
        const networkId = await cardanoWallet.getNetworkId();
        if (!networkId) {
            throw new Error('Could not determine network');
        }
        wallet.set('NetworkID', networkId);
        console.log('Network ID:', networkId);

        // Get the reward addresses
        const rewardAddresses = await cardanoWallet.getRewardAddresses();
        if (!rewardAddresses || rewardAddresses.length === 0) {
            throw new Error('Could not determine reward addresses');
        }

        // Use the first reward address
        const stakeAddress = rewardAddresses[0];
        wallet.set('StakeAddress', stakeAddress);
        console.log('Stake Address:', stakeAddress);

        return true; // Success
    } catch (error) {
        console.error('Failed to connect wallet:', error);
        return false; // Failure
    }
	// END USER CODE
}
