// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} wallet
 * @returns {Promise.<boolean>}
 */
export async function JS_Wallet_Connect(wallet) {
	// BEGIN USER CODE
    const walletIdentifier = wallet.get('_id');
    if (!cardano || !cardano[walletIdentifier]) {
        console.error('Wallet not found');
        return false;
    }

    try {
        // Re-enable the wallet and retrieve the wallet API object
        const cardanoWallet = await cardano[walletIdentifier].enable();
        if (!cardanoWallet) {
            throw new Error('Could not enable wallet');
        }

        console.info('Cardano Wallet enabled:', cardanoWallet);

        // Get the network ID
        const networkId = await cardanoWallet.getNetworkId();
        if (networkId === null || networkId === undefined) {
            throw new Error('Could not determine network');
        }
        wallet.set('NetworkID', networkId);
        if (networkId == 0) {
            wallet.set('CardanoNetwork', 'Preprod')
        } else {
            wallet.set('CardanoNetwork', 'Mainnet')
        }
        console.log('Network ID:', networkId);

        // Get the reward addresses
        const rewardAddresses = await cardanoWallet.getRewardAddresses();
        if (!rewardAddresses || rewardAddresses.length === 0) {
            throw new Error('Could not determine reward addresses');
        }

        // Use the first reward address
        const stakeAddress = rewardAddresses[0];
        wallet.set('StakeAddress', stakeAddress);
        console.log('Stake Address:', stakeAddress);

        // Get base address (first used address, fallback to unused)
        const usedAddresses = await cardanoWallet.getUsedAddresses();
        let baseAddress;
        if (usedAddresses.length > 0) {
            baseAddress = usedAddresses[0];
        } else {
            const unusedAddresses = await cardanoWallet.getUnusedAddresses();
            if (unusedAddresses.length === 0) {
                throw new Error('No addresses available in wallet');
            }
            baseAddress = unusedAddresses[0];
        }
        wallet.set('BaseAddress', baseAddress);
        console.log('Base Address:', baseAddress);        

        return true; // Success
    } catch (error) {
        console.error('Failed to connect wallet:', error);
        return false; // Failure
    }
	// END USER CODE
}
