// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.address.Address;
import com.bloxbean.cardano.client.util.HexUtil;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import cardanowallet.Utils;

public class ConvertHexToBech32 extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String HexString;

	public ConvertHexToBech32(
		IContext context,
		java.lang.String _hexString
	)
	{
		super(context);
		this.HexString = _hexString;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			if (this.HexString == null || this.HexString.isEmpty()) {
				throw new Exception("Hex string is empty");
			}
			Address address = new Address(HexUtil.decodeHexString(this.HexString));
			return address.toBech32();
		} catch (Exception e) {
			throw new Exception("Error converting hex to bech32: " + e.getMessage());
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ConvertHexToBech32";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
