// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.common.cbor.CborSerializationUtil;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class DecodeCborToJSON extends CustomJavaAction<java.lang.String>
{
	private java.lang.String CBORHexString;

	public DecodeCborToJSON(IContext context, java.lang.String CBORHexString)
	{
		super(context);
		this.CBORHexString = CBORHexString;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		final ILogNode LOG = Core.getLogger("CardanoWallet");

		try {
			byte[] cborData = hexStringToByteArray(CBORHexString);
			Transaction transaction = Transaction.deserialize(cborData)
			LOG.info(transaction.toString());
			return CborSerializationUtil.deserialize(cborData).toString();
        } catch (Exception e) {
            throw new RuntimeException("Error decoding CBOR data", e);
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DecodeCborToJSON";
	}

	// BEGIN EXTRA CODE
	private byte[] hexStringToByteArray(String s) {
        int len = s.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {
            data[i / 2] = (byte) ((Character.digit(s.charAt(i), 16) << 4)
                                + Character.digit(s.charAt(i + 1), 16));
        }
        return data;
    }
	// END EXTRA CODE
}
