// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import static com.bloxbean.cardano.client.common.ADAConversionUtil.lovelaceToAda;
import java.math.BigInteger;
import java.util.List;
import com.bloxbean.cardano.client.api.common.OrderEnum;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.backend.api.AccountService;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.backend.model.AccountHistory;
import com.bloxbean.cardano.client.backend.model.AccountInformation;
import com.bloxbean.cardano.client.common.model.Network;
import com.bloxbean.cardano.client.common.model.Networks;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

public class JA_Account_GetBalances extends CustomJavaAction<java.lang.Void>
{
	/** @deprecated use Wallet.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Wallet;
	private final cardanowallet.proxies.Wallet Wallet;

	public JA_Account_GetBalances(
		IContext context,
		IMendixObject _wallet
	)
	{
		super(context);
		this.__Wallet = _wallet;
		this.Wallet = _wallet == null ? null : cardanowallet.proxies.Wallet.initialize(getContext(), _wallet);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		this.blockfrostProjectId = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
		String networkString = this.Wallet.getCardanonetwork().name();
		setNetworkDetails(networkString);		
		
		BFBackendService backendService =
					new BFBackendService(this.blockfrostUrl, this.blockfrostProjectId);

		// use the account service to get the account information
		AccountService accountService = backendService.getAccountService();
		Result<AccountInformation> accountBalanceResult = accountService.getAccountInformation(this.Wallet.getStakeAddress());
		LOG.debug("====");
		LOG.debug(this.Wallet.getStakeAddress());
		LOG.debug("====");
		Result<List<AccountHistory>> accountHistoryResult = accountService.getAccountHistory(this.Wallet.getStakeAddress(), 10, 1, OrderEnum.desc);
		LOG.debug(accountBalanceResult);
		LOG.debug(accountHistoryResult);

		// use http api request to get the balance
		BigInteger accountBalance = accountBalanceResult.isSuccessful()
			? new BigInteger(accountBalanceResult.getValue().getControlledAmount())
			: new BigInteger("0");

		this.Wallet.setBalance(lovelaceToAda(accountBalance));
		return null;
		// Print the balance
		// return new java.math.BigDecimal(10.0);
		// return accountBalance.getAmount();

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Account_GetBalances";
	}

	// BEGIN EXTRA CODE

	private Network selectedNetwork;
	private String blockfrostUrl;
	private String blockfrostProjectId = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
	public static ILogNode LOG = Core.getLogger(cardanowallet.proxies.constants.Constants.getLogNodeName());

	private void setNetworkDetails(String cardanoNetworkString) {
		cardanoNetworkString =  cardanoNetworkString.length() > 0 ? cardanoNetworkString: "mainnet";
		if(cardanoNetworkString.equalsIgnoreCase("preprod")) {
			this.selectedNetwork = Networks.preprod();
			this.blockfrostUrl = Constants.BLOCKFROST_PREPROD_URL;
		} else if(cardanoNetworkString.equalsIgnoreCase("testnet")) {
			this.selectedNetwork = Networks.testnet();
			this.blockfrostUrl = Constants.BLOCKFROST_TESTNET_URL;
		} else if(cardanoNetworkString.equalsIgnoreCase("preview")) {
			this.blockfrostUrl = Constants.BLOCKFROST_PREVIEW_URL;
			this.selectedNetwork = Networks.preview();
		} else {
			this.selectedNetwork = Networks.mainnet();
			this.blockfrostUrl = Constants.BLOCKFROST_MAINNET_URL;	
		}
	}

	/**
	 * EncryptDecryptMnemonic
	 */

	private String API_KEY = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();	

	// END EXTRA CODE
}
