// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.address.AddressProvider;
import com.bloxbean.cardano.client.api.util.PolicyUtil;
import com.bloxbean.cardano.client.common.model.Networks;
import com.bloxbean.cardano.client.crypto.VerificationKey;
import com.bloxbean.cardano.client.transaction.spec.Policy;
import com.bloxbean.cardano.client.transaction.spec.script.ScriptAtLeast;
import com.bloxbean.cardano.client.transaction.spec.script.ScriptPubkey;
import com.bloxbean.cardano.client.util.HexUtil;
import com.bloxbean.cardano.client.util.JsonUtil;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import cardanowallet.EncryptDecryptMnemonic;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_CreatePolicy extends CustomJavaAction<java.lang.String>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(WitnessList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __WitnessList;
	private final java.util.List<cardanowallet.proxies.Witness> WitnessList;
	/** @deprecated use Policy.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Policy;
	private final cardanowallet.proxies.Policy Policy;
	private final java.lang.String PolicyPassphrase;

	public JA_CreatePolicy(
		IContext context,
		java.util.List<IMendixObject> _witnessList,
		IMendixObject _policy,
		java.lang.String _policyPassphrase
	)
	{
		super(context);
		this.__WitnessList = _witnessList;
		this.WitnessList = java.util.Optional.ofNullable(_witnessList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(witnessListElement -> cardanowallet.proxies.Witness.initialize(getContext(), witnessListElement))
			.collect(java.util.stream.Collectors.toList());
		this.__Policy = _policy;
		this.Policy = _policy == null ? null : cardanowallet.proxies.Policy.initialize(getContext(), _policy);
		this.PolicyPassphrase = _policyPassphrase;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		Policy policy = PolicyUtil.createMultiSigScriptAllPolicy(this.Policy.getName(),1);
	    this.Policy.setPolicyId(policy.getPolicyId());
	    this.Policy.setScriptHash(JsonUtil.getPrettyJson(policy.getPolicyScript()));
	    String cborHex = policy.getPolicyKeys().get(0).getCborHex();
	    EncryptDecryptMnemonic encryptDecryptMnemonic = new EncryptDecryptMnemonic();
	    this.Policy.setPKey(encryptDecryptMnemonic.encrypt(cborHex, this.PolicyPassphrase));
	    return cborHex;
	    
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CreatePolicy";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
