// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import static com.bloxbean.cardano.client.common.ADAConversionUtil.adaToLovelace;
import com.bloxbean.cardano.client.backend.api.DefaultProtocolParamsSupplier;
import com.bloxbean.cardano.client.backend.api.DefaultUtxoSupplier;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.cip.cip20.MessageMetadata;
import com.bloxbean.cardano.client.common.model.Network;
import com.bloxbean.cardano.client.common.model.Networks;
import com.bloxbean.cardano.client.function.Output;
import com.bloxbean.cardano.client.function.TxBuilder;
import com.bloxbean.cardano.client.function.TxBuilderContext;
import com.bloxbean.cardano.client.function.helper.AuxDataProviders;
import com.bloxbean.cardano.client.function.helper.BalanceTxBuilders;
import com.bloxbean.cardano.client.function.helper.InputBuilders;
import com.bloxbean.cardano.client.quicktx.QuickTxBuilder;
import com.bloxbean.cardano.client.quicktx.Tx;
import com.bloxbean.cardano.client.api.model.Amount;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import static com.bloxbean.cardano.client.common.CardanoConstants.LOVELACE;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;

public class JA_CardanoTransaction_UnSigned extends CustomJavaAction<java.lang.String>
{
	private java.lang.String SenderAddress;
	private java.lang.String ReceiverAddress;
	private java.math.BigDecimal AmountInAda;
	private cardanowallet.proxies.Enum_CardanoNetwork CardanoNetwork;
	private java.lang.String TransactionMetaData;

	public JA_CardanoTransaction_UnSigned(IContext context, java.lang.String SenderAddress, java.lang.String ReceiverAddress, java.math.BigDecimal AmountInAda, java.lang.String CardanoNetwork, java.lang.String TransactionMetaData)
	{
		super(context);
		this.SenderAddress = SenderAddress;
		this.ReceiverAddress = ReceiverAddress;
		this.AmountInAda = AmountInAda;
		this.CardanoNetwork = CardanoNetwork == null ? null : cardanowallet.proxies.Enum_CardanoNetwork.valueOf(CardanoNetwork);
		this.TransactionMetaData = TransactionMetaData;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		final ILogNode LOG = Core.getLogger("CardanoWallet");
		
		LOG.debug("Start Execution of JA_CardanoTransaction_UnSigned");

		String blockfrostUrl;
		Network selectedNetwork;

		String networkString = CardanoNetwork.name();
		if(networkString.equalsIgnoreCase("preprod")) {
			selectedNetwork = Networks.preprod();
			blockfrostUrl = Constants.BLOCKFROST_PREPROD_URL;
		} else if(networkString.equalsIgnoreCase("testnet")) {
			selectedNetwork = Networks.testnet();
			blockfrostUrl = Constants.BLOCKFROST_TESTNET_URL;
		} else if(networkString.equalsIgnoreCase("preview")) {
			blockfrostUrl = Constants.BLOCKFROST_PREVIEW_URL;
			selectedNetwork = Networks.preview();
		} else {
			selectedNetwork = Networks.mainnet();
			blockfrostUrl = Constants.BLOCKFROST_MAINNET_URL;
		}

		String senderAddress = this.SenderAddress;
		String receiverAddress1 = this.ReceiverAddress;

		String bfProjectId = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
		
/*		BFBackendService backendService =
				new BFBackendService(blockfrostUrl, bfProjectId);

		Output output1 = Output.builder()
				.address(receiverAddress1)
				.assetName(LOVELACE)
				.qty(adaToLovelace(this.Amount.doubleValue()))
				.build();
		
		//MessageMetadata metadata = MessageMetadata.create()
		//.add(this.TransactionMetaData);
				
		TxBuilder txBuilder = output1.outputBuilder()
				.buildInputs(InputBuilders.createFromSender(senderAddress, senderAddress))
				//.andThen(AuxDataProviders.metadataProvider(metadata))
				.andThen(BalanceTxBuilders.balanceTx(senderAddress, 1));
		
		DefaultUtxoSupplier utxoSupplier = new DefaultUtxoSupplier(backendService.getUtxoService());
		DefaultProtocolParamsSupplier protocolParamsSupplier = new DefaultProtocolParamsSupplier(backendService.getEpochService());
		
		Transaction unsignedTransaction = TxBuilderContext.init(utxoSupplier, protocolParamsSupplier)
											.build(txBuilder);
		
		unsignedTransaction.setAuxiliaryData(null);
		unsignedTransaction.setWitnessSet(null);
		LOG.info("Unsigned Transaction : " + unsignedTransaction.toJson());
		
		String unsignedTransactionCbor = unsignedTransaction.serializeToHex();
		LOG.debug("Finish Execution of JA_CardanoTransaction_UnSigned");
		return unsignedTransactionCbor;*/
		Tx tx1 = new Tx()
                .payToAddress(receiverAddress1, Amount.ada(this.AmountInAda.doubleValue()))
                .attachMetadata(MessageMetadata.create().add("This is a test message 2"))
                .from(senderAddress);
		
		BFBackendService backendService =
				new BFBackendService(blockfrostUrl, bfProjectId);
		
        QuickTxBuilder quickTxBuilder = new QuickTxBuilder(backendService);
        
        return quickTxBuilder
        		.compose(tx1)
        		.feePayer(senderAddress)
        		.build()
        		.serializeToHex();
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CardanoTransaction_UnSigned";
	}

	// BEGIN EXTRA CODE
	
	// END EXTRA CODE
}
