// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.address.AddressProvider;
import com.bloxbean.cardano.client.common.model.Networks;
import com.bloxbean.cardano.client.crypto.VerificationKey;
import com.bloxbean.cardano.client.transaction.spec.script.ScriptAtLeast;
import com.bloxbean.cardano.client.transaction.spec.script.ScriptPubkey;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_CreatePolicy extends CustomJavaAction<IMendixObject>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(WitnessList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __WitnessList;
	private final java.util.List<cardanowallet.proxies.Witness> WitnessList;
	/** @deprecated use Policy.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Policy;
	private final cardanowallet.proxies.Policy Policy;

	public JA_CreatePolicy(
		IContext context,
		java.util.List<IMendixObject> _witnessList,
		IMendixObject _policy
	)
	{
		super(context);
		this.__WitnessList = _witnessList;
		this.WitnessList = java.util.Optional.ofNullable(_witnessList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(witnessListElement -> cardanowallet.proxies.Witness.initialize(getContext(), witnessListElement))
			.collect(java.util.stream.Collectors.toList());
		this.__Policy = _policy;
		this.Policy = _policy == null ? null : cardanowallet.proxies.Policy.initialize(getContext(), _policy);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		ScriptAtLeast scriptAtLeast = new ScriptAtLeast(this.Policy.getAllowedWitnesses());

								// .addScript(scriptPubkey1)
								// .addScript(scriptPubkey2)
								// .addScript(scriptPubkey3);
		this.WitnessList.forEach(witness -> 
		{
			// AddressProvider.getBaseAddress(witness, Networks.preprod()).toBech32();
			// String receiverAddress = witness.getReceiverAddress();
			
			// VerificationKey witnessVerificationKey = VerificationKey.create(receiverAddress.getBytes());
			// ScriptPubkey scriptPubkey = ScriptPubkey.create(witnessVerificationKey);
			// scriptAtLeast.addScript(scriptPubkey);
		});
		return this.Policy.getMendixObject();
		// throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CreatePolicy";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
