  // This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.address.AddressProvider;
import com.bloxbean.cardano.client.api.ProtocolParamsSupplier;
import com.bloxbean.cardano.client.api.UtxoSupplier;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.backend.api.BackendService;
import com.bloxbean.cardano.client.backend.api.DefaultProtocolParamsSupplier;
import com.bloxbean.cardano.client.backend.api.DefaultUtxoSupplier;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.common.model.Networks;
import com.bloxbean.cardano.client.crypto.KeyGenUtil;
import com.bloxbean.cardano.client.crypto.Keys;
import com.bloxbean.cardano.client.crypto.SecretKey;
import com.bloxbean.cardano.client.crypto.VerificationKey;
import com.bloxbean.cardano.client.function.Output;
import com.bloxbean.cardano.client.function.TxBuilder;
import com.bloxbean.cardano.client.function.TxBuilderContext;
import com.bloxbean.cardano.client.function.TxSigner;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.bloxbean.cardano.client.transaction.spec.script.ScriptAtLeast;
import com.bloxbean.cardano.client.transaction.spec.script.ScriptPubkey;
import static com.bloxbean.cardano.client.common.ADAConversionUtil.adaToLovelace;
import static com.bloxbean.cardano.client.common.CardanoConstants.LOVELACE;
import static com.bloxbean.cardano.client.function.helper.BalanceTxBuilders.balanceTx;
import static com.bloxbean.cardano.client.function.helper.InputBuilders.createFromSender;
import static com.bloxbean.cardano.client.function.helper.SignerProviders.signerFrom;

public class JA_Cardano_MultiSignTransfer extends CustomJavaAction<java.lang.String>
{
	public JA_Cardano_MultiSignTransfer(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		//make sure you run it before the designing approaching you've taken.
		// verify in blockfrost
		// findout how to get the verification key from the public key. (without having to use the mnemonic - privateKey)
		// write your findings in the development channel.
		// make a plan of how to create a thing that the round table has done. (continue with your design process using roundtable approach)
		// ask questions in discord channel when you're not sure and Mr. Dorus will answer them.
		// Use ECLIPSE (IDE) to write your code and test it before you implement it in Mendix.


				//First account
				// String account1Mnemonic = "lemon trick vintage actor maze remain cool viable fence identify say popular supply hole afford measure expire degree happy subject badge air tiny mansion";
				String account1Mnemonic = "wealth tattoo weapon conduct picture grain exclude arch match install movie drift bid poverty judge anchor patch dismiss chalk film during gasp work hedgehog";
				Account account1 = new Account(Networks.preprod(), account1Mnemonic);
				//Second account
				// String account2Mnemonic = "begin cannon garage pattern bread later swamp choice obtain embody shaft switch tiger claw bird company feature glue favorite present castle hat album pause";
				String account2Mnemonic  = "hurdle once message walnut basket door cruise illness armed coin armed extend trim acquire wash decide beyond burden glory omit page address theory warrior";
				Account account2 = new Account(Networks.preprod(), account2Mnemonic);
				//Third account payment key
				/*Keys keys = KeyGenUtil.generateKey();
				VerificationKey verificationKey = keys.getVkey();
				SecretKey secretKey = keys.getSkey();
				String paymentSigningKeyCborHex = secretKey.getCborHex();
				LOG.info("Payment Signing Key CBOR Hex:: "+paymentSigningKeyCborHex);*/
				//Payment Signing Key CBOR Hex:: 5820645c673be575f9d12993a225752632754de2c136e1dab99cb3c9fadeb17f51b6
				String paymentSigningKeyCborHex = "5820645c673be575f9d12993a225752632754de2c136e1dab99cb3c9fadeb17f51b6";
				SecretKey secretKey = new SecretKey(paymentSigningKeyCborHex);  
				VerificationKey verificationKey = KeyGenUtil.getPublicKeyFromPrivateKey(secretKey);
				//Derive verification key for account1 and account2
				LOG.info("Public key bytes:: account1 :: "+account1.publicKeyBytes());
				LOG.info("account1 reciverAddress :: "+account1.baseAddress());

				LOG.info("Script Address:: account2 "+account2.publicKeyBytes());
				VerificationKey account1Vk = VerificationKey.create(account1.publicKeyBytes());
				LOG.info("Verification keys:: account1 reciverAddress ::"+ account1Vk);
				VerificationKey account2Vk = VerificationKey.create(account2.publicKeyBytes());
				//Create native script with type=sig for each verification key
				ScriptPubkey scriptPubkey1 = ScriptPubkey.create(account1Vk);
				LOG.info("Script Address:: account2 "+scriptPubkey1);
				ScriptPubkey scriptPubkey2 = ScriptPubkey.create(account2Vk);
				ScriptPubkey scriptPubkey3 = ScriptPubkey.create(verificationKey);
				//Create multi-sig script with type "atLeast"
				ScriptAtLeast scriptAtLeast = new ScriptAtLeast(2)
								.addScript(scriptPubkey1)
								.addScript(scriptPubkey2)
								.addScript(scriptPubkey3);
				//addr_test1wr6fvn0y3rumu30ch3lrggss4vmgsr65cxly2t6dulvwamq3y98et
				//addr_test1wqrz07e4fgjy3cznt8x60pfh7r70ltv4yyumvpyvja45tmgg9v48z
				String scriptAddress = AddressProvider.getEntAddress(scriptAtLeast, Networks.testnet()).toBech32();
				LOG.info("Script Address:: "+scriptAddress);
				// scriptAddress = "addr_test1wqrz07e4fgjy3cznt8x60pfh7r70ltv4yyumvpyvja45tmgg9v48z";
				//load script address with funds

				// For Blockfrost
				String bf_projectId = "preprodoqh304gIgYVyyNtpiv3TkpMsBQttuHzr";
				BackendService backendService = new BFBackendService(Constants.BLOCKFROST_PREPROD_URL, bf_projectId);
				// For Koios
				//BackendService backendService = new KoiosBackendService(KOIOS_TESTNET_URL);
				//Define outputs
				String address1 = account1.baseAddress();
				Output output1 = Output.builder()
								.address(address1)
								.assetName(LOVELACE)
								.qty(adaToLovelace(2))
								.build();
				String address2 = account2.baseAddress();
				Output output2 = Output.builder()
								.address(address2)
								.assetName(LOVELACE)
								.qty(adaToLovelace(2))
								.build();
				TxBuilder txBuilder = output1.outputBuilder()
								.and(output2.outputBuilder()) 
								.buildInputs(createFromSender(scriptAddress, scriptAddress))
								.andThen((context, txn) -> {
										txn.getWitnessSet().getNativeScripts().add(scriptAtLeast);
								})
								.andThen(balanceTx(scriptAddress, 2));
				UtxoSupplier utxoSupplier = new DefaultUtxoSupplier(backendService.getUtxoService());
				ProtocolParamsSupplier protocolParamsSupplier = new DefaultProtocolParamsSupplier(backendService.getEpochService());
				
				// retrieve the account from the mnemonic again. inorder for the signing to be done.
				// next step is to build the transaction and have it signed off by the person who initiated this.
				// save the mnenomic or the private key in the database for future use.
				// make sure that the mnemonic is encrypted and stored in the database.
				TxSigner signers = signerFrom(account1)
								.andThen(signerFrom(secretKey)); //3rd sk/vk pair
				Transaction signedTransaction = TxBuilderContext.init(utxoSupplier, protocolParamsSupplier)
								.buildAndSign(txBuilder, signers);
				Result<String> result = backendService.getTransactionService().submitTransaction(signedTransaction.serialize());
				// System.out.println(result);
				LOG.info(result);
		
		return result.getValue();
		//throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Cardano_MultiSignTransfer";
	}

	// BEGIN EXTRA CODE
	public static ILogNode LOG = Core.getLogger("LandanoTest");
	// END EXTRA CODE
}
