// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JA_CardanoTransaction_UnSigned extends CustomJavaAction<java.lang.String>
{
	private java.lang.String SenderAddress;
	private java.lang.String ReceiverAddress;
	private java.lang.Long Amount;
	private cardanowallet.proxies.Enum_CardanoNetwork CardanoNetwork;
	private java.lang.String TransactionMetaData;

	public JA_CardanoTransaction_UnSigned(IContext context, java.lang.String SenderAddress, java.lang.String ReceiverAddress, java.lang.Long Amount, java.lang.String CardanoNetwork, java.lang.String TransactionMetaData)
	{
		super(context);
		this.SenderAddress = SenderAddress;
		this.ReceiverAddress = ReceiverAddress;
		this.Amount = Amount;
		this.CardanoNetwork = CardanoNetwork == null ? null : cardanowallet.proxies.Enum_CardanoNetwork.valueOf(CardanoNetwork);
		this.TransactionMetaData = TransactionMetaData;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CardanoTransaction_UnSigned";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
