// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.address.AddressProvider;
import com.bloxbean.cardano.client.common.model.Networks;
import com.bloxbean.cardano.client.crypto.VerificationKey;
import com.bloxbean.cardano.client.transaction.spec.script.ScriptAtLeast;
import com.bloxbean.cardano.client.transaction.spec.script.ScriptPubkey;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_CreatePolicy extends CustomJavaAction<IMendixObject>
{
	private java.util.List<IMendixObject> __WitnessList;
	private java.util.List<cardanowallet.proxies.Witness> WitnessList;
	private IMendixObject __Policy;
	private cardanowallet.proxies.Policy Policy;

	public JA_CreatePolicy(IContext context, java.util.List<IMendixObject> WitnessList, IMendixObject Policy)
	{
		super(context);
		this.__WitnessList = WitnessList;
		this.__Policy = Policy;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.WitnessList = java.util.Optional.ofNullable(this.__WitnessList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(__WitnessListElement -> cardanowallet.proxies.Witness.initialize(getContext(), __WitnessListElement))
			.collect(java.util.stream.Collectors.toList());

		this.Policy = this.__Policy == null ? null : cardanowallet.proxies.Policy.initialize(getContext(), __Policy);

		// BEGIN USER CODE
		ScriptAtLeast scriptAtLeast = new ScriptAtLeast(this.Policy.getAllowedWitnesses());

								// .addScript(scriptPubkey1)
								// .addScript(scriptPubkey2)
								// .addScript(scriptPubkey3);
		this.WitnessList.forEach(witness -> 
		{
			// AddressProvider.getBaseAddress(witness, Networks.preprod()).toBech32();
			// String receiverAddress = witness.getReceiverAddress();
			
			// VerificationKey witnessVerificationKey = VerificationKey.create(receiverAddress.getBytes());
			// ScriptPubkey scriptPubkey = ScriptPubkey.create(witnessVerificationKey);
			// scriptAtLeast.addScript(scriptPubkey);
		});
		return this.Policy.getMendixObject();
		// throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CreatePolicy";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
