// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.address.Address;
import com.bloxbean.cardano.client.address.AddressProvider;
import com.bloxbean.cardano.client.api.util.PolicyUtil;
import com.bloxbean.cardano.client.common.model.Networks;
import com.bloxbean.cardano.client.crypto.VerificationKey;
import com.bloxbean.cardano.client.transaction.spec.Policy;
import com.bloxbean.cardano.client.transaction.spec.script.ScriptAtLeast;
import com.bloxbean.cardano.client.transaction.spec.script.ScriptPubkey;
import com.bloxbean.cardano.client.util.HexUtil;
import com.bloxbean.cardano.client.util.JsonUtil;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import cardanowallet.EncryptDecryptMnemonic;
import cardanowallet.Utils;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_CreateMultiSig extends CustomJavaAction<java.lang.String>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(WitnessList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __WitnessList;
	private final java.util.List<cardanowallet.proxies.Witness> WitnessList;
	/** @deprecated use Policy.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Policy;
	private final cardanowallet.proxies.Policy Policy;
	private final java.lang.String PolicyPassphrase;
	private final java.lang.Long RequiredSigners;
	private final cardanowallet.proxies.SigningMandate SigningMandate;

	public JA_CreateMultiSig(
		IContext context,
		java.util.List<IMendixObject> _witnessList,
		IMendixObject _policy,
		java.lang.String _policyPassphrase,
		java.lang.Long _requiredSigners,
		java.lang.String _signingMandate
	)
	{
		super(context);
		this.__WitnessList = _witnessList;
		this.WitnessList = java.util.Optional.ofNullable(_witnessList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(witnessListElement -> cardanowallet.proxies.Witness.initialize(getContext(), witnessListElement))
			.collect(java.util.stream.Collectors.toList());
		this.__Policy = _policy;
		this.Policy = _policy == null ? null : cardanowallet.proxies.Policy.initialize(getContext(), _policy);
		this.PolicyPassphrase = _policyPassphrase;
		this.RequiredSigners = _requiredSigners;
		this.SigningMandate = _signingMandate == null ? null : cardanowallet.proxies.SigningMandate.valueOf(_signingMandate);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			ScriptAtLeast scriptAtLeast = new ScriptAtLeast(this.Policy.getRequiredSigners());
			this.utils = new Utils(this.Policy.getCardanonetwork().name()); // derive the network from the policy. meaning that at UI specify an input for cardano network. Also this will give you validation for the witnesses to be of the same network like the script network. 
			this.WitnessList.forEach(witness -> 
			{
				String witnessAddressHex;
				try {
					witnessAddressHex = Utils.ConvertPublicAddressToHex(witness.getAddress());
					witness.setPublicKeyHash(witnessAddressHex);
					ScriptPubkey scriptPubkey = new ScriptPubkey(witnessAddressHex);
					scriptAtLeast.addScript(scriptPubkey);
				} catch (Exception e) {
					throw new RuntimeException("Error converting public address to hex: " + e.getMessage());
				}
			});
		    this.Policy.setScriptHash(JsonUtil.getPrettyJson(scriptAtLeast));
		    String nativeScriptBech32Address = AddressProvider.getEntAddress(scriptAtLeast, this.utils.getCardanoNetwork()).toBech32();
		    this.Policy.setAddress(nativeScriptBech32Address);
		    this.Policy.setAddressHex(Utils.ConvertPublicAddressToHex(nativeScriptBech32Address));
	        
			return nativeScriptBech32Address;
		} catch (Exception e) {
			throw new Exception("Error creating multisig policy: " + e.getMessage());
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CreateMultiSig";
	}

	// BEGIN EXTRA CODE
	public static ILogNode LOG = Core.getLogger("LandanoTest");
	public Utils utils;
	// END EXTRA CODE
}
