// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import cardanowallet.EncryptDecryptMnemonic;

public class JA_DecryptMnemonic extends CustomJavaAction<java.lang.String>
{
	private java.lang.String EncryptedMnemonic;
	private java.lang.String Passphrase;

	public JA_DecryptMnemonic(IContext context, java.lang.String EncryptedMnemonic, java.lang.String Passphrase)
	{
		super(context);
		this.EncryptedMnemonic = EncryptedMnemonic;
		this.Passphrase = Passphrase;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		EncryptDecryptMnemonic encryptDecryptMnemonic = new EncryptDecryptMnemonic();
		return encryptDecryptMnemonic.decrypt(this.EncryptedMnemonic, this.Passphrase);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_DecryptMnemonic";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
