// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.util.HexUtil;
import com.bloxbean.cardano.client.util.Tuple;
import com.bloxbean.cardano.client.api.util.AssetUtil;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JA_GetAssetName extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String AssetUnit;

	public JA_GetAssetName(
		IContext context,
		java.lang.String _assetUnit
	)
	{
		super(context);
		this.AssetUnit = _assetUnit;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        Tuple<String, String> policyIdAssetName = AssetUtil.getPolicyIdAndAssetName(this.AssetUnit);
        String assetName = new String( HexUtil.decodeHexString(policyIdAssetName._2));
        return assetName;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GetAssetName";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
