// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_GetAccountBalances extends CustomJavaAction<java.math.BigDecimal>
{
	private IMendixObject __Parameter;
	private cardanowallet.proxies.Wallet Parameter;

	public JA_GetAccountBalances(IContext context, IMendixObject Parameter)
	{
		super(context);
		this.__Parameter = Parameter;
	}

	@java.lang.Override
	public java.math.BigDecimal executeAction() throws Exception
	{
		this.Parameter = this.__Parameter == null ? null : cardanowallet.proxies.Wallet.initialize(getContext(), __Parameter);

		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GetAccountBalances";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
