// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JA_GenerateAssetUnitId extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String AssetName;
	private final java.lang.String PolicyId;

	public JA_GenerateAssetUnitId(
		IContext context,
		java.lang.String _assetName,
		java.lang.String _policyId
	)
	{
		super(context);
		this.AssetName = _assetName;
		this.PolicyId = _policyId;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuilder AssetHex = new StringBuilder();
	    for (char ch : AssetName.toCharArray()) {
	        AssetHex.append(String.format("%02x", (int) ch));
	    }
	    return PolicyId + AssetHex.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GenerateAssetUnitId";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
