// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.nio.charset.StandardCharsets;
import com.bloxbean.cardano.client.transaction.spec.Asset;
import com.bloxbean.cardano.client.util.HexUtil;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JA_HexToString extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String HexInput;

	public JA_HexToString(
		IContext context,
		java.lang.String _hexInput
	)
	{
		super(context);
		this.HexInput = _hexInput;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        // Convert hex to bytes using Cardano Client Library
        byte[] bytes = HexUtil.decodeHexString(HexInput);

        // Convert byte array to a readable string
        return new String(bytes, StandardCharsets.UTF_8).trim();		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_HexToString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
