// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.util.HashMap;
import java.util.Map;
import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.bloxbean.cardano.client.util.HexUtil;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import cardanowallet.EncryptDecryptMnemonic;
import cardanowallet.Utils;

public class JA_MultiSig_Transaction_Sign extends CustomJavaAction<java.lang.Boolean>
{
	/** @deprecated use TransactionSigning.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __TransactionSigning;
	private final cardanowallet.proxies.TransactionSigning TransactionSigning;
	/** @deprecated use Wallet.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Wallet;
	private final cardanowallet.proxies.Wallet Wallet;
	private final java.lang.String WalletPassword;

	public JA_MultiSig_Transaction_Sign(
		IContext context,
		IMendixObject _transactionSigning,
		IMendixObject _wallet,
		java.lang.String _walletPassword
	)
	{
		super(context);
		this.__TransactionSigning = _transactionSigning;
		this.TransactionSigning = _transactionSigning == null ? null : cardanowallet.proxies.TransactionSigning.initialize(getContext(), _transactionSigning);
		this.__Wallet = _wallet;
		this.Wallet = _wallet == null ? null : cardanowallet.proxies.Wallet.initialize(getContext(), _wallet);
		this.WalletPassword = _walletPassword;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			Utils utils = new Utils(this.Wallet.getCardanonetwork().toString().toLowerCase());
			
			String mnemonic = EncryptDecryptMnemonic.decrypt(this.Wallet.getMnemonicEncrypted(), this.WalletPassword);
			
			Account signingAccount = new Account(utils.getCardanoNetwork(), mnemonic);
			Transaction transaction = Transaction.deserialize(HexUtil.decodeHexString(this.TransactionSigning.getUnsignedCBOR()));

			LOG.debug("transactio deserialized");
			LOG.debug(transaction);
			Transaction witnessSignedTransaction = signingAccount.sign(transaction);
			this.TransactionSigning.setSignedCBOR(witnessSignedTransaction.serializeToHex()); //serialize the original transaction so witnesses can sign it independently.
		} catch (Exception e) {
			LOG.error("Error in JA_MultiSig_Txn_Witness_Signing");
			LOG.error(e);
			return false;
		}
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_MultiSig_Transaction_Sign";
	}

	// BEGIN EXTRA CODE
	public static ILogNode LOG = Core.getLogger("LandanoTest");
	// END EXTRA CODE
}
