// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.bloxbean.cardano.client.transaction.spec.TransactionOutput;
import com.bloxbean.cardano.client.transaction.spec.script.ScriptAtLeast;
import com.bloxbean.cardano.client.util.HexUtil;
import com.bloxbean.cardano.client.util.JsonUtil;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.module.SimpleModule;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import cardanowallet.EncryptDecryptMnemonic;
import cardanowallet.Utils;
import cardanowallet.TransactionOutputDeserializer;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_MultiSig_Txn_Witness_Signing extends CustomJavaAction<java.lang.Boolean>
{
	/** @deprecated use Txn.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Txn;
	private final cardanowallet.proxies.Txn Txn;
	/** @deprecated use TxnSigning.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __TxnSigning;
	private final cardanowallet.proxies.TxnSigning TxnSigning;
	/** @deprecated use Wallet.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Wallet;
	private final cardanowallet.proxies.Wallet Wallet;
	private final java.lang.String WalletPassword;
	private final java.lang.String EncryptedMnemonic;

	public JA_MultiSig_Txn_Witness_Signing(
		IContext context,
		IMendixObject _txn,
		IMendixObject _txnSigning,
		IMendixObject _wallet,
		java.lang.String _walletPassword,
		java.lang.String _encryptedMnemonic
	)
	{
		super(context);
		this.__Txn = _txn;
		this.Txn = _txn == null ? null : cardanowallet.proxies.Txn.initialize(getContext(), _txn);
		this.__TxnSigning = _txnSigning;
		this.TxnSigning = _txnSigning == null ? null : cardanowallet.proxies.TxnSigning.initialize(getContext(), _txnSigning);
		this.__Wallet = _wallet;
		this.Wallet = _wallet == null ? null : cardanowallet.proxies.Wallet.initialize(getContext(), _wallet);
		this.WalletPassword = _walletPassword;
		this.EncryptedMnemonic = _encryptedMnemonic;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			var utils = new Utils("preprod");
			/*// Decrypt the mnemonic
			EncryptDecryptMnemonic decryptMnemonic = new EncryptDecryptMnemonic();
			String mnemonic = decryptMnemonic.decrypt(this.EncryptedMnemonic, this.Passphrase);*/
			EncryptDecryptMnemonic decryptMnemonic = new EncryptDecryptMnemonic();
			String mnemonic = decryptMnemonic.decrypt(this.EncryptedMnemonic, this.WalletPassword);
			System.out.println("================================");
			System.out.println(mnemonic);
			LOG.info(mnemonic);
			System.out.println("================================");
			LOG.info(utils.getCardanoNetwork());
			System.out.println(utils.getCardanoNetwork());
			Account signingAccount = new Account(utils.getCardanoNetwork(), mnemonic);
			/*
			 * USE CBOR since its native to Cardano, avoid JSON deserialization
			 * It has a known issue as there are some bytes array. So we need to add some custom deserializer to handle bytes
			 * 
			 * 
			var objectMapper = new ObjectMapper();
			SimpleModule module = new SimpleModule();
			module.addDeserializer(TransactionOutput.class, new TransactionOutputDeserializer());
			objectMapper.registerModule(module);
			Transaction transaction = objectMapper.readValue(this.Txn.getSerializedTxn(), Transaction.class); */
			Transaction transaction = Transaction.deserialize(HexUtil.decodeHexString(this.Txn.getCborOriginal()));

			LOG.info("transactio deserialized");
			LOG.info(transaction);
			Transaction witnessSignedTransaction = signingAccount.sign(transaction);
			this.TxnSigning.setSignedTxnCbor(witnessSignedTransaction.serializeToHex()); //serialize the original transaction so witnesses can sign it independently.
		} catch (Exception e) {
			LOG.error("Error in JA_MultiSig_Txn_Witness_Signing");
			LOG.error(e);
			return false;
		}
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_MultiSig_Txn_Witness_Signing";
	}

	// BEGIN EXTRA CODE
	public static ILogNode LOG = Core.getLogger("LandanoTest");
	// END EXTRA CODE
}
