// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.bloxbean.cardano.client.common.model.Network;
import com.bloxbean.cardano.client.common.model.Networks;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import org.apache.commons.lang3.SystemUtils;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.backend.api.DefaultProtocolParamsSupplier;
import com.bloxbean.cardano.client.backend.api.DefaultUtxoSupplier;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.cip.cip25.NFT;
import com.bloxbean.cardano.client.cip.cip25.NFTFile;
import com.bloxbean.cardano.client.cip.cip25.NFTMetadata;
import com.bloxbean.cardano.client.function.TxBuilder;
import com.bloxbean.cardano.client.function.TxBuilderContext;
import com.bloxbean.cardano.client.function.helper.SignerProviders;
import com.bloxbean.cardano.client.metadata.helper.JsonNoSchemaToMetadataConverter;
import com.bloxbean.cardano.client.quicktx.QuickTxBuilder;
import com.bloxbean.cardano.client.quicktx.Tx;
import com.bloxbean.cardano.client.transaction.spec.Asset;
import com.bloxbean.cardano.client.transaction.spec.MultiAsset;
import com.bloxbean.cardano.client.transaction.spec.Policy;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.bloxbean.cardano.client.transaction.spec.TransactionOutput;
import com.bloxbean.cardano.client.transaction.spec.Value;
import com.bloxbean.cardano.client.api.util.PolicyUtil;
import static com.bloxbean.cardano.client.function.helper.AuxDataProviders.metadataProvider;
import static com.bloxbean.cardano.client.function.helper.BalanceTxBuilders.balanceTx;
import static com.bloxbean.cardano.client.function.helper.InputBuilders.createFromSender;
import static com.bloxbean.cardano.client.function.helper.MintCreators.mintCreator;
import static com.bloxbean.cardano.client.function.helper.OutputBuilders.createFromMintOutput;
import static com.bloxbean.cardano.client.function.helper.SignerProviders.signerFrom;
import static com.bloxbean.cardano.client.common.CardanoConstants.LOVELACE;
import static com.bloxbean.cardano.client.common.ADAConversionUtil.adaToLovelace;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import cardanowallet.EncryptDecryptMnemonic;
import com.bloxbean.cardano.client.util.JsonUtil;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.bloxbean.cardano.client.metadata.Metadata;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadataList;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadataMap;
import co.nstant.in.cbor.model.UnicodeString;

public class JA_MintNFTNew extends CustomJavaAction<java.lang.String>
{
	public JA_MintNFTNew(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		/*setCardanoNetwork(CardanoNetwork.name()); //sets up blockfrostUrl and selectedNetwork, 
		String bfProjectId = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
        BFBackendService backendService = new BFBackendService(this.blockfrostUrl, bfProjectId);
        
		sender = new Account(this.selectedNetwork, (new EncryptDecryptMnemonic()).decrypt(this.EncryptedMnemonic, this.Passphrase));
        String senderAddress = sender.baseAddress();
        LOG.info("Sender address"+senderAddress);

        Policy policy = PolicyUtil.createMultiSigScriptAllPolicy(this.MxNFT.getPolicyName(),1);
        Asset asset = new Asset(this.MxNFT.getAssetName(), BigInteger.valueOf(1));
        NFT nft = NFT.create()
        		.assetName(asset.getName())
        		.name(this.MxNFT.getName())
        		.image(this.MxNFT.getIPFSImage())
        		.description(this.MxNFT.getDescription());
        
        String stringMetadata = this.MxNFT.getJSONMetadata();
        if(!stringMetadata.startsWith("{")) {
        	stringMetadata = "{"+stringMetadata+"}";
        }*/
        /*stringMetadata = """"
        	{
                    "town": "SpatialUnit ABC1234",
                    "name": "SpatialUnit ABC1234",
                    "files": [
                      {
                        "src": "https://arweave4.net/1IBE9yoqVSJcxZNJACpcCwuJETQB5iXayOq-1JZbIdc",
                        "name": "Landano Arkly Package4",
                        "mediaType": "application/gzip"
                      },
                      {
                        "src": "https://wearehere.com/1IBE9yoqVSJcxZNJACpcCwuJETQB5iXayOq-1JZbIdc",
                        "name": "Landano Arkly Package File 2",
                        "mediaType": "application/gzip"
                      }
                    ],
                    "image": "ipfs://someimageurl-2",
                    "ensi": "country",
                    "description": "A unique spatial unit representation.",
                    "Farm5": {
                      "chicken": "400m2",
                      "dog": "SU123454",
                      "math": "2D",
                      "brain": [
                        {
                          "eyes": "two eyes",
                          "nose": "two nostrils",
                          "ears": "two"
                        },
                        {'p yyyyyyyyyycs    34edc bbyh'
                          "eyes": "",
                          "nose": "",
                          "teeth": 32
                        }
                      ]
                    }
                  }
        """;*/
       /* var version = this.MxNFT.getVersion().toString();
		NFTMetadata nftMetadata = NFTMetadata.create()
				.version(version)
                .addNFT(policy.getPolicyId(), nft);

        Tx tx = new Tx()
                .mintAssets(policy.getPolicyScript(), asset, sender.baseAddress())
                .attachMetadata(nftMetadata) 
                .from(sender.baseAddress());
        QuickTxBuilder quickTxBuilder = new QuickTxBuilder(backendService);
        Result<String> result = quickTxBuilder.compose(tx)
                .withSigner(SignerProviders.signerFrom(sender))
                .withSigner(SignerProviders.signerFrom(policy))
                .complete();

        System.out.println(result);

        if (result.isSuccessful())
            LOG.info("Transaction Id: " + result.getValue());
        else
            LOG.info("Transaction failed: " + result);
        return result.getValue();*/
		return "";
	
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_MintNFTNew";
	}

	// BEGIN EXTRA CODE
	private Network selectedNetwork;
    private String blockfrostUrl = Constants.BLOCKFROST_MAINNET_URL;
	private Account sender;
    public static ILogNode LOG = Core.getLogger("LandanoTest - NFT Creation");

    public void setCardanoNetwork(String networkString) {
        if(networkString.equalsIgnoreCase("preprod")) {
			selectedNetwork = Networks.preprod();
			blockfrostUrl = Constants.BLOCKFROST_PREPROD_URL;
		} else if(networkString.equalsIgnoreCase("testnet")) {
			selectedNetwork = Networks.testnet();
			blockfrostUrl = Constants.BLOCKFROST_TESTNET_URL;
		} else if(networkString.equalsIgnoreCase("preview")) {
			blockfrostUrl = Constants.BLOCKFROST_PREVIEW_URL;
			selectedNetwork = Networks.preview();
		} else {
			selectedNetwork = Networks.mainnet();
			blockfrostUrl = Constants.BLOCKFROST_MAINNET_URL;
		}
    }
    
    
    public static NFT generateNFTMetadata(NFT nft, Map<String, Object> properties) {
//        Policy policy = PolicyUtil.createMultiSigScriptAllPolicy(policyName, 1);
        
//        NFT nft = NFT.create().assetName(assetName);
    	LOG.info("NFT Map::::::");
    	LOG.info(nft.getMap());

    	for (Map.Entry<String, Object> entry : properties.entrySet()) {
            String key = entry.getKey();
            Object value = entry.getValue();
            
            if (key.equals("files") && value instanceof List) {
                List<Map<String, Object>> files = (List<Map<String, Object>>) value;
                for (Map<String, Object> file : files) {
                    nft.addFile(NFTFile.create()
                            .name((String) file.get("name"))
                            .mediaType((String) file.get("mediaType"))
                            .src((String) file.get("src")));
                }
            } else if (value instanceof Map) {
                nft.property(key, (Map<String, Object>) value);
            } else if (value instanceof List) {
//                nft.property(key, (List<Object>) value);
            } else {
                nft.property(key, value.toString());
            }
        }
        return nft;
    }
    
    public static Map<String, Object> createPropertiesFromJsonString(String jsonString) throws Exception {
    	System.out.println(jsonString);
        ObjectMapper mapper = new ObjectMapper();
        JsonNode rootNode = mapper.readTree(jsonString);
        System.out.println(rootNode);
        
        return convertJsonNodeToMap(rootNode);
    }

    private static Map<String, Object> convertJsonNodeToMap(JsonNode node) {
        Map<String, Object> map = new HashMap<>();
        
        Iterator<Map.Entry<String, JsonNode>> fields = node.fields();
        while (fields.hasNext()) {
            Map.Entry<String, JsonNode> entry = fields.next();
            String key = entry.getKey();
            JsonNode value = entry.getValue();
            
            map.put(key, convertJsonNodeToObject(value));
        }
        
        return map;
    }
    
    private static Object convertJsonNodeToObject(JsonNode node) {
        if (node.isObject()) {
            return convertJsonNodeToMap(node);
        } else if (node.isArray()) {
            List<Object> list = new ArrayList<>();
            for (JsonNode element : node) {
                list.add(convertJsonNodeToObject(element));
            }
            return list;
        } else if (node.isNumber()) {
            return node.numberValue();
        } else if (node.isBoolean()) {
            return node.booleanValue();
        } else if (node.isNull()) {
            return null;
        } else {
            return node.asText();
        }
    }

    private static List<Object> convertJsonNodeToList(JsonNode node) {
        List<Object> list = new ArrayList<>();
        
        for (JsonNode element : node) {
            if (element.isObject()) {
                list.add(convertJsonNodeToMap(element));
            } else if (element.isArray()) {
                list.add(convertJsonNodeToList(element));
            } else if (element.isNumber()) {
                list.add(element.numberValue());
            } else if (element.isBoolean()) {
                list.add(element.booleanValue());
            } else {
                list.add(element.asText());
            }
        }
        
        return list;
    }
    
    /*
     import com.bloxbean.cardano.client.api.util.PolicyUtil;
import com.bloxbean.cardano.client.cip.cip25.NFT;
import com.bloxbean.cardano.client.cip.cip25.NFTFile;
import com.bloxbean.cardano.client.cip.cip25.NFTMetadata;
import com.bloxbean.cardano.client.transaction.spec.Policy;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.core.JsonProcessingException;

import java.math.BigInteger;
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;

public class DynamicNFTMetadataGenerator {

    public static Map<String, Object> createPropertiesFromJsonString(String jsonString) throws JsonProcessingException {
        ObjectMapper mapper = new ObjectMapper();
        JsonNode rootNode = mapper.readTree(jsonString);
        
        return convertJsonNodeToMap(rootNode);
    }

    private static Map<String, Object> convertJsonNodeToMap(JsonNode node) {
        Map<String, Object> map = new HashMap<>();
        
        Iterator<Map.Entry<String, JsonNode>> fields = node.fields();
        while (fields.hasNext()) {
            Map.Entry<String, JsonNode> entry = fields.next();
            String key = entry.getKey();
            JsonNode value = entry.getValue();
            
            map.put(key, convertJsonNodeToObject(value));
        }
        
        return map;
    }

    private static Object convertJsonNodeToObject(JsonNode node) {
        if (node.isObject()) {
            return convertJsonNodeToMap(node);
        } else if (node.isArray()) {
            List<Object> list = new ArrayList<>();
            for (JsonNode element : node) {
                list.add(convertJsonNodeToObject(element));
            }
            return list;
        } else if (node.isNumber()) {
            return node.numberValue();
        } else if (node.isBoolean()) {
            return node.booleanValue();
        } else if (node.isNull()) {
            return null;
        } else {
            return node.asText();
        }
    }

    public static NFTMetadata generateNFTMetadata(String policyName, String assetName, Map<String, Object> properties) {
        Policy policy = PolicyUtil.createMultiSigScriptAllPolicy(policyName, 1);
        
        NFT nft = NFT.create().assetName(assetName);
        
        for (Map.Entry<String, Object> entry : properties.entrySet()) {
            String key = entry.getKey();
            Object value = entry.getValue();
            
            if (key.equals("files") && value instanceof List) {
                List<Map<String, Object>> files = (List<Map<String, Object>>) value;
                for (Map<String, Object> file : files) {
                    nft.addFile(NFTFile.create()
                            .name((String) file.get("name"))
                            .mediaType((String) file.get("mediaType"))
                            .src((String) file.get("src")));
                }
            } else if (value instanceof Map) {
                nft.property(key, (Map<String, Object>) value);
            } else if (value instanceof List) {
                nft.property(key, (List<Object>) value);
            } else {
                nft.property(key, value.toString());
            }
        }

        return NFTMetadata.create().addNFT(policy.getPolicyId(), nft);
    }

    public static void main(String[] args) {
        String jsonString = """
        {
          "la_spatialunit_nft_id_6": {
            "town": "SpatialUnit ABC1234",
            "name": "SpatialUnit ABC1234",
            "files": [
              {
                "src": "https://arweave4.net/1IBE9yoqVSJcxZNJACpcCwuJETQB5iXayOq-1JZbIdc",
                "name": "Landano Arkly Package4",
                "mediaType": "application/gzip"
              },
              {
                "src": "https://wearehere.com/1IBE9yoqVSJcxZNJACpcCwuJETQB5iXayOq-1JZbIdc",
                "name": "Landano Arkly Package File 2",
                "mediaType": "application/gzip"
              }
            ],
            "image": "ipfs://someimageurl-2",
            "ensi": "country",
            "description": "A unique spatial unit representation.",
            "Farm5": {
              "chicken": "400m2",
              "dog": "SU123454",
              "math": "2D",
              "brain": [
                {
                  "eyes": "two eyes",
                  "nose": "two nostrils",
                  "ears": "two"
                },
                {
                  "eyes": "",
                  "nose": "",
                  "teeth": 32
                }
              ]
            }
          }
        }
        """;

        try {
            Map<String, Object> properties = createPropertiesFromJsonString(jsonString);
            String assetName = properties.keySet().iterator().next(); // Get the first (and only) key
            Map<String, Object> nftProperties = (Map<String, Object>) properties.get(assetName);
            
            NFTMetadata nftMetadata = generateNFTMetadata("policy-ld-6", assetName, nftProperties);
            System.out.println(nftMetadata.toString());
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }
    }
}
     * 
     * */
    
	// END EXTRA CODE
}
