// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.bloxbean.cardano.client.common.model.Network;
import com.bloxbean.cardano.client.common.model.Networks;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.math.BigInteger;
import java.util.List;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.backend.api.DefaultProtocolParamsSupplier;
import com.bloxbean.cardano.client.backend.api.DefaultUtxoSupplier;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.cip.cip25.NFT;
import com.bloxbean.cardano.client.cip.cip25.NFTFile;
import com.bloxbean.cardano.client.cip.cip25.NFTMetadata;
import com.bloxbean.cardano.client.function.TxBuilder;
import com.bloxbean.cardano.client.function.TxBuilderContext;
import com.bloxbean.cardano.client.transaction.spec.Asset;
import com.bloxbean.cardano.client.transaction.spec.MultiAsset;
import com.bloxbean.cardano.client.transaction.spec.Policy;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.bloxbean.cardano.client.transaction.spec.TransactionOutput;
import com.bloxbean.cardano.client.transaction.spec.Value;
import com.bloxbean.cardano.client.api.util.PolicyUtil;
import static com.bloxbean.cardano.client.function.helper.AuxDataProviders.metadataProvider;
import static com.bloxbean.cardano.client.function.helper.BalanceTxBuilders.balanceTx;
import static com.bloxbean.cardano.client.function.helper.InputBuilders.createFromSender;
import static com.bloxbean.cardano.client.function.helper.MintCreators.mintCreator;
import static com.bloxbean.cardano.client.function.helper.OutputBuilders.createFromMintOutput;
import static com.bloxbean.cardano.client.function.helper.SignerProviders.signerFrom;
import static com.bloxbean.cardano.client.common.CardanoConstants.LOVELACE;
import static com.bloxbean.cardano.client.common.ADAConversionUtil.adaToLovelace;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import cardanowallet.EncryptDecryptMnemonic;

public class JA_Mint_NFT extends CustomJavaAction<java.lang.String>
{
	private java.lang.String EncryptedMnemonic;
	private java.lang.String Passphrase;
	private java.lang.String ReceiverAddress;
	private cardanowallet.proxies.Enum_CardanoNetwork CardanoNetwork;
	private java.lang.String Metadata;
	private IMendixObject __MxNFT;
	private cardanowallet.proxies.NFT MxNFT;
	private java.lang.String IPFSImage;

	public JA_Mint_NFT(IContext context, java.lang.String EncryptedMnemonic, java.lang.String Passphrase, java.lang.String ReceiverAddress, java.lang.String CardanoNetwork, java.lang.String Metadata, IMendixObject MxNFT, java.lang.String IPFSImage)
	{
		super(context);
		this.EncryptedMnemonic = EncryptedMnemonic;
		this.Passphrase = Passphrase;
		this.ReceiverAddress = ReceiverAddress;
		this.CardanoNetwork = CardanoNetwork == null ? null : cardanowallet.proxies.Enum_CardanoNetwork.valueOf(CardanoNetwork);
		this.Metadata = Metadata;
		this.__MxNFT = MxNFT;
		this.IPFSImage = IPFSImage;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.MxNFT = this.__MxNFT == null ? null : cardanowallet.proxies.NFT.initialize(getContext(), __MxNFT);

		// BEGIN USER CODE
		// throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		setCardanoNetwork(CardanoNetwork.name());
		sender = new Account(this.selectedNetwork, (new EncryptDecryptMnemonic()).decrypt(this.EncryptedMnemonic, this.Passphrase));
        String senderAddress = sender.baseAddress();
        LOG.info(senderAddress);

		String receiverAddress = this.ReceiverAddress;

        Policy policy = PolicyUtil.createMultiSigScriptAllPolicy(this.MxNFT.getPolicyName(), 1);

        //Multi asset and NFT metadata
        MultiAsset multiAsset = new MultiAsset();
        multiAsset.setPolicyId(policy.getPolicyId());
        Asset asset = new Asset(this.MxNFT.getName(), BigInteger.valueOf(1));
        multiAsset.getAssets().add(asset);
        
        NFT nft = NFT.create()
                .assetName(asset.getName())
                .name(asset.getName())
                .image(this.MxNFT.getIPFSImage())
                .mediaType("image/png")
                .addFile(NFTFile.create()
                        .name("Landano Arkly Package")
                        .mediaType("application/gzip")
                        .src("https://arweave.net/1IBE9yoqVSJcxZNJACpcCwuJETQB5iXayOq-1JZbIdc"))
                .description("This is a test NFT");
        nft.property("landano_spatial_unit", this.MxNFT.getJSONMetadata());

        NFTMetadata nftMetadata = NFTMetadata.create()
        		.version(1)
                .addNFT(policy.getPolicyId(), nft);

        Value value = Value.builder()
                .coin(BigInteger.ZERO)
                .multiAssets(List.of(multiAsset)).build();

        TransactionOutput mintOutput = TransactionOutput.builder()
                .address(this.ReceiverAddress)
                .value(value).build();

        TxBuilder txBuilder =
                createFromMintOutput(mintOutput)
                        .buildInputs(createFromSender(senderAddress, senderAddress))
                        .andThen(mintCreator(policy.getPolicyScript(), multiAsset))
                        .andThen(metadataProvider(nftMetadata))
                        .andThen(balanceTx(senderAddress, 2));
        String bfProjectId = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
        BFBackendService backendService =
		        new BFBackendService(this.blockfrostUrl, bfProjectId);

        DefaultUtxoSupplier utxoSupplier = new DefaultUtxoSupplier(backendService.getUtxoService());
		DefaultProtocolParamsSupplier protocolParamsSupplier = new DefaultProtocolParamsSupplier(backendService.getEpochService());
        

        Transaction signedTransaction = TxBuilderContext.init(utxoSupplier, protocolParamsSupplier)
                .buildAndSign(txBuilder, signerFrom(sender).andThen(signerFrom(policy)));

        LOG.info(signedTransaction);
        Result<String> result = backendService.getTransactionService().submitTransaction(signedTransaction.serialize());
        LOG.info(result);

        if (result.isSuccessful())
            LOG.info("Transaction Id: " + result.getValue());
        else
            LOG.info("Transaction failed: " + result);
        return result.getValue();


		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Mint_NFT";
	}

	// BEGIN EXTRA CODE
	private Network selectedNetwork;
    private String blockfrostUrl = Constants.BLOCKFROST_MAINNET_URL;
	private Account sender;
    public static ILogNode LOG = Core.getLogger("LandanoTest - NFT Creation");

    public void setCardanoNetwork(String networkString) {
        if(networkString.equalsIgnoreCase("preprod")) {
			selectedNetwork = Networks.preprod();
			blockfrostUrl = Constants.BLOCKFROST_PREPROD_URL;
		} else if(networkString.equalsIgnoreCase("testnet")) {
			selectedNetwork = Networks.testnet();
			blockfrostUrl = Constants.BLOCKFROST_TESTNET_URL;
		} else if(networkString.equalsIgnoreCase("preview")) {
			blockfrostUrl = Constants.BLOCKFROST_PREVIEW_URL;
			selectedNetwork = Networks.preview();
		} else {
			selectedNetwork = Networks.mainnet();
			blockfrostUrl = Constants.BLOCKFROST_MAINNET_URL;
		}
    }
	// END EXTRA CODE
}
