// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.exception.CborDeserializationException;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.bloxbean.cardano.client.util.HexUtil;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import cardanowallet.Utils;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_MultiSig_Transaction_Submit extends CustomJavaAction<java.lang.String>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(TxnSigningList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __TxnSigningList;
	private final java.util.List<cardanowallet.proxies.TxnSigning> TxnSigningList;
	/** @deprecated use Txn.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Txn;
	private final cardanowallet.proxies.Txn Txn;
	private final cardanowallet.proxies.Enum_CardanoNetwork CardanoNetwork;

	public JA_MultiSig_Transaction_Submit(
		IContext context,
		java.util.List<IMendixObject> _txnSigningList,
		IMendixObject _txn,
		java.lang.String _cardanoNetwork
	)
	{
		super(context);
		this.__TxnSigningList = _txnSigningList;
		this.TxnSigningList = java.util.Optional.ofNullable(_txnSigningList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(txnSigningListElement -> cardanowallet.proxies.TxnSigning.initialize(getContext(), txnSigningListElement))
			.collect(java.util.stream.Collectors.toList());
		this.__Txn = _txn;
		this.Txn = _txn == null ? null : cardanowallet.proxies.Txn.initialize(getContext(), _txn);
		this.CardanoNetwork = _cardanoNetwork == null ? null : cardanowallet.proxies.Enum_CardanoNetwork.valueOf(_cardanoNetwork);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        Transaction transaction = Transaction.deserialize(HexUtil.decodeHexString(this.Txn.getCborOriginal()));
		var utils = new Utils(this.CardanoNetwork.getCaption());
		this.TxnSigningList.forEach(TxnSigningMx -> 
		{
			Transaction witnessSignedTxn;
			try {
				witnessSignedTxn = Transaction.deserialize(HexUtil.decodeHexString(TxnSigningMx.getSignedTxnCbor()));
				LOG.info("=======witnessSignedTx===witnessSet===");
				LOG.info(witnessSignedTxn.getWitnessSet());
				LOG.info("=======witnessSignedTx===VKeywitnessSet===");
				LOG.info(witnessSignedTxn.getWitnessSet().getVkeyWitnesses());
				LOG.info("=======witnessSignedTx===VKeywitnessSet===get(0)=====");
				LOG.info(witnessSignedTxn.getWitnessSet().getVkeyWitnesses().get(0));
				transaction.getWitnessSet().getVkeyWitnesses().add(witnessSignedTxn.getWitnessSet().getVkeyWitnesses().get(0));
			} catch (CborDeserializationException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				LOG.error(e);
			}
		});
		
        Result<String> result = utils.backendService.getTransactionService().submitTransaction(transaction.serialize());

        System.out.println(result);
        if(result.isSuccessful()) {
        	this.Txn.setCborFinal(transaction.serializeToHex());
        	this.Txn.setTransactionId(result.getValue());
        	utils.waitForTransactionHash(result); // we'll need a queuing system.
        } else {
        	LOG.error("Transaction failed");
        	LOG.error(result);
        	return "";
        }
        return result.getValue();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_MultiSig_Transaction_Submit";
	}

	// BEGIN EXTRA CODE
	public static ILogNode LOG = Core.getLogger("LandanoTest");

	// END EXTRA CODE
}
