// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.math.BigInteger;
import java.util.List;
import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.backend.api.DefaultProtocolParamsSupplier;
import com.bloxbean.cardano.client.backend.api.DefaultUtxoSupplier;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.cip.cip25.NFT;
import com.bloxbean.cardano.client.cip.cip25.NFTFile;
import com.bloxbean.cardano.client.cip.cip25.NFTMetadata;
import com.bloxbean.cardano.client.common.model.Network;
import com.bloxbean.cardano.client.common.model.Networks;
import com.bloxbean.cardano.client.function.TxBuilder;
import com.bloxbean.cardano.client.function.TxBuilderContext;
import com.bloxbean.cardano.client.transaction.spec.Asset;
import com.bloxbean.cardano.client.transaction.spec.MultiAsset;
import com.bloxbean.cardano.client.transaction.spec.Policy;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.bloxbean.cardano.client.transaction.spec.TransactionOutput;
import com.bloxbean.cardano.client.transaction.spec.Value;
import com.bloxbean.cardano.client.api.util.PolicyUtil;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import static com.bloxbean.cardano.client.function.helper.AuxDataProviders.metadataProvider;
import static com.bloxbean.cardano.client.function.helper.BalanceTxBuilders.balanceTx;
import static com.bloxbean.cardano.client.function.helper.InputBuilders.createFromSender;
import static com.bloxbean.cardano.client.function.helper.MintCreators.mintCreator;
import static com.bloxbean.cardano.client.function.helper.OutputBuilders.createFromMintOutput;
import static com.bloxbean.cardano.client.function.helper.SignerProviders.signerFrom;

public class JA_MintToken extends CustomJavaAction<java.lang.String>
{
	public JA_MintToken(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        String senderMnemonic = "degree rice inherit lawn oyster say world mushroom city race sunset market repeat main happy image fiscal property nice forest spawn vanish table fragile";
        Account sender = new Account(Networks.preprod(), senderMnemonic);
        String senderAddress = sender.baseAddress();
        System.out.printf(senderAddress);

        String receiverAddress = "addr_test1qrhxkr2cp33gqdyxhpsrlmh6p0vpg7l98s2cxqyyy682v33xt2un9n7rv7xxslmlhfvfs3ugzgnzyhzun99tg2mhqrzsydpxx8";

        Policy policy = PolicyUtil.createMultiSigScriptAllPolicy("policy-ld-1", 1);

        //Multi asset and NFT metadata
        MultiAsset multiAsset = new MultiAsset();
        multiAsset.setPolicyId(policy.getPolicyId());
        Asset asset = new Asset("TestNFT_LD", BigInteger.valueOf(1));
        multiAsset.getAssets().add(asset);

        NFT nft = NFT.create()
                .assetName(asset.getName())
                .name(asset.getName())
                .image("ipfs://Qmcv6hwtmdVumrNeb42R1KmCEWdYWGcqNgs17Y3hj6CkP4")
                .mediaType("image/png")
                .addFile(NFTFile.create()
                        .name("file-1")
                        .mediaType("image/png")
                        .src("ipfs/Qmcv6hwtmdVumrNeb42R1KmCEWdYWGcqNgs17Y3hj6CkP4"))
                .description("This is a test NFT");

        NFTMetadata nftMetadata = NFTMetadata.create()
        		.version(1)
                .addNFT(policy.getPolicyId(), nft);

        Value value = Value.builder()
                .coin(BigInteger.ZERO)
                .multiAssets(List.of(multiAsset)).build();

        TransactionOutput mintOutput = TransactionOutput.builder()
                .address(receiverAddress)
                .value(value).build();

        TxBuilder txBuilder =
                createFromMintOutput(mintOutput)
                        .buildInputs(createFromSender(senderAddress, senderAddress))
                        .andThen(mintCreator(policy.getPolicyScript(), multiAsset))
                        .andThen(metadataProvider(nftMetadata))
                        .andThen(balanceTx(senderAddress, 2));

		String blockfrostUrl;
		Network selectedNetwork;

		String networkString = "preprod";
		if(networkString.equalsIgnoreCase("preprod")) {
			selectedNetwork = Networks.preprod();
			blockfrostUrl = Constants.BLOCKFROST_PREPROD_URL;
		} else if(networkString.equalsIgnoreCase("testnet")) {
			selectedNetwork = Networks.testnet();
			blockfrostUrl = Constants.BLOCKFROST_TESTNET_URL;
		} else if(networkString.equalsIgnoreCase("preview")) {
			blockfrostUrl = Constants.BLOCKFROST_PREVIEW_URL;
			selectedNetwork = Networks.preview();
		} else {
			selectedNetwork = Networks.mainnet();
			blockfrostUrl = Constants.BLOCKFROST_MAINNET_URL;
		}

		String bfProjectId = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();		
        BFBackendService backendService =
		        new BFBackendService(blockfrostUrl, bfProjectId);

        DefaultUtxoSupplier utxoSupplier = new DefaultUtxoSupplier(backendService.getUtxoService());
		DefaultProtocolParamsSupplier protocolParamsSupplier = new DefaultProtocolParamsSupplier(backendService.getEpochService());
        

        Transaction signedTransaction = TxBuilderContext.init(utxoSupplier, protocolParamsSupplier)
                .buildAndSign(txBuilder, signerFrom(sender).andThen(signerFrom(policy)));

        System.out.println(signedTransaction);
        Result<String> result = backendService.getTransactionService().submitTransaction(signedTransaction.serialize());
        System.out.println(result);

        if (result.isSuccessful())
            System.out.println("Transaction Id: " + result.getValue());
        else
            System.out.println("Transaction failed: " + result);
        return result.getValue();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_MintToken";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
