// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import static com.bloxbean.cardano.client.common.CardanoConstants.LOVELACE;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import com.bloxbean.cardano.client.function.Output;
import com.bloxbean.cardano.client.function.TxBuilder;
import com.bloxbean.cardano.client.function.TxBuilderContext;
import com.bloxbean.cardano.client.function.TxOutputBuilder;
import com.bloxbean.cardano.client.function.helper.BalanceTxBuilders;
import com.bloxbean.cardano.client.function.helper.InputBuilders;
import com.bloxbean.cardano.client.transaction.spec.script.NativeScript;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import cardanowallet.Utils;
import cardanowallet.proxies.RecipientNP;
import cardanowallet.proxies.TransactionNP;

public class JA_MultiSig_Transaction_Build extends CustomJavaAction<java.lang.String>
{
	/** @deprecated use Transaction.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Transaction;
	private final cardanowallet.proxies.TransactionNP Transaction;

	public JA_MultiSig_Transaction_Build(
		IContext context,
		IMendixObject _transaction
	)
	{
		super(context);
		this.__Transaction = _transaction;
		this.Transaction = _transaction == null ? null : cardanowallet.proxies.TransactionNP.initialize(getContext(), _transaction);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		Utils utils = new Utils(this.Transaction.getTransactionNP_Policy().getCardanonetwork().toString().toLowerCase());
		NativeScript nativeScript = NativeScript.deserializeJson(this.Transaction.getTransactionNP_Policy().getScriptJSON());
		
		List<IMendixObject> recipients = Core.retrieveByPath(getContext(), this.Transaction.getMendixObject(), cardanowallet.proxies.RecipientNP.MemberNames.RecipientNP_TransactionNP.toString());
        
		List<Output> outputs = new ArrayList<Output>(); 
		
		for (IMendixObject obj : recipients) {
            RecipientNP recipient = RecipientNP.initialize(this.getContext(), obj);
			Output output = Output.builder()
	                .address(recipient.getAddress())
	                .assetName(LOVELACE)
	                .qty(BigInteger.valueOf(recipient.getAmountInLong())).build();
			outputs.add(output);
		}
		
		TxOutputBuilder outputBuilder = outputs.get(0).outputBuilder();
		for (int i = 1; i < outputs.size(); i++) {
		    outputBuilder = outputBuilder.and(outputs.get(i).outputBuilder());
		}
		
		String scriptAddress = this.Transaction.getTransactionNP_Policy().getAddress();
		
		TxBuilder txBuilder = outputBuilder
			    .buildInputs(InputBuilders.createFromSender(scriptAddress, scriptAddress))
			    .andThen((context, transaction) -> {
			        // Add your script manually for now
			        transaction.getWitnessSet().getNativeScripts().add(nativeScript);
			    })
			    .andThen(BalanceTxBuilders.balanceTx(scriptAddress, this.Transaction.getTransactionNP_Policy().getWitnessCount()));		

		        
        
        com.bloxbean.cardano.client.transaction.spec.Transaction transaction = TxBuilderContext.init(utils.utxoSupplier, utils.protocolParamsSupplier).build(txBuilder);
        return transaction.serializeToHex(); //serialize the original transaction so witnesses can sign it independently.
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_MultiSig_Transaction_Build";
	}

	// BEGIN EXTRA CODE
	public static ILogNode LOG = Core.getLogger("LandanoTest");

	// END EXTRA CODE
}
