// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.bloxbean.cardano.client.common.model.Network;
import com.bloxbean.cardano.client.common.model.Networks;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.commons.lang3.SystemUtils;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.backend.api.DefaultProtocolParamsSupplier;
import com.bloxbean.cardano.client.backend.api.DefaultUtxoSupplier;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.cip.cip25.NFT;
import com.bloxbean.cardano.client.cip.cip25.NFTFile;
import com.bloxbean.cardano.client.cip.cip25.NFTMetadata;
import com.bloxbean.cardano.client.function.TxBuilder;
import com.bloxbean.cardano.client.function.TxBuilderContext;
import com.bloxbean.cardano.client.function.helper.SignerProviders;
import com.bloxbean.cardano.client.metadata.helper.JsonNoSchemaToMetadataConverter;
import com.bloxbean.cardano.client.quicktx.QuickTxBuilder;
import com.bloxbean.cardano.client.quicktx.Tx;
import com.bloxbean.cardano.client.transaction.spec.Asset;
import com.bloxbean.cardano.client.transaction.spec.MultiAsset;
import com.bloxbean.cardano.client.transaction.spec.Policy;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.bloxbean.cardano.client.transaction.spec.TransactionOutput;
import com.bloxbean.cardano.client.transaction.spec.Value;
import com.bloxbean.cardano.client.api.util.PolicyUtil;
import static com.bloxbean.cardano.client.function.helper.AuxDataProviders.metadataProvider;
import static com.bloxbean.cardano.client.function.helper.BalanceTxBuilders.balanceTx;
import static com.bloxbean.cardano.client.function.helper.InputBuilders.createFromSender;
import static com.bloxbean.cardano.client.function.helper.MintCreators.mintCreator;
import static com.bloxbean.cardano.client.function.helper.OutputBuilders.createFromMintOutput;
import static com.bloxbean.cardano.client.function.helper.SignerProviders.signerFrom;
import static com.bloxbean.cardano.client.common.CardanoConstants.LOVELACE;
import static com.bloxbean.cardano.client.common.ADAConversionUtil.adaToLovelace;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import cardanowallet.EncryptDecryptMnemonic;
import com.bloxbean.cardano.client.util.JsonUtil;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.bloxbean.cardano.client.metadata.Metadata;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadataList;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadataMap;
import co.nstant.in.cbor.model.UnicodeString;

public class JA_Mint_NFT2 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String EncryptedMnemonic;
	private java.lang.String Passphrase;
	private java.lang.String ReceiverAddress;
	private cardanowallet.proxies.Enum_CardanoNetwork CardanoNetwork;
	private java.lang.String Metadata;
	private IMendixObject __MxNFT;
	private cardanowallet.proxies.NFT MxNFT;
	private java.lang.String IPFSImage;
	private java.util.List<IMendixObject> __NFTFileList;
	private java.util.List<cardanowallet.proxies.NFTFile> NFTFileList;

	public JA_Mint_NFT2(IContext context, java.lang.String EncryptedMnemonic, java.lang.String Passphrase, java.lang.String ReceiverAddress, java.lang.String CardanoNetwork, java.lang.String Metadata, IMendixObject MxNFT, java.lang.String IPFSImage, java.util.List<IMendixObject> NFTFileList)
	{
		super(context);
		this.EncryptedMnemonic = EncryptedMnemonic;
		this.Passphrase = Passphrase;
		this.ReceiverAddress = ReceiverAddress;
		this.CardanoNetwork = CardanoNetwork == null ? null : cardanowallet.proxies.Enum_CardanoNetwork.valueOf(CardanoNetwork);
		this.Metadata = Metadata;
		this.__MxNFT = MxNFT;
		this.IPFSImage = IPFSImage;
		this.__NFTFileList = NFTFileList;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.MxNFT = this.__MxNFT == null ? null : cardanowallet.proxies.NFT.initialize(getContext(), __MxNFT);

		this.NFTFileList = java.util.Optional.ofNullable(this.__NFTFileList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(__NFTFileListElement -> cardanowallet.proxies.NFTFile.initialize(getContext(), __NFTFileListElement))
			.collect(java.util.stream.Collectors.toList());

		// BEGIN USER CODE
		setCardanoNetwork(CardanoNetwork.name()); //sets up blockfrostUrl and selectedNetwork, 
		String bfProjectId = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
        BFBackendService backendService = new BFBackendService(this.blockfrostUrl, bfProjectId);
        
		sender = new Account(this.selectedNetwork, (new EncryptDecryptMnemonic()).decrypt(this.EncryptedMnemonic, this.Passphrase));
        String senderAddress = sender.baseAddress();
        LOG.info("Sender address"+senderAddress);

        Policy policy = PolicyUtil.createMultiSigScriptAllPolicy(this.MxNFT.getPolicyName(),1);
        Asset asset = new Asset(this.MxNFT.getAssetName(), BigInteger.valueOf(1));
        NFT nft = NFT.create()
        		.assetName(asset.getName())
        		.name(this.MxNFT.getName())
        		.image(this.MxNFT.getIPFSImage())
        		.description(this.MxNFT.getDescription());
        
        String stringMetadata = this.MxNFT.getJSONMetadata();
        if(!stringMetadata.startsWith("{")) {
        	stringMetadata = "{"+stringMetadata+"}";
        }
		try {
            Map<String, Object> properties = createPropertiesFromJsonString(stringMetadata);
            System.out.println(properties);

            // Now you can use this properties map to generate NFT metadata
            generateNFTMetadata(nft, properties);
            System.out.println(nft.toString());
            // Add Files
            for (cardanowallet.proxies.NFTFile entry : this.NFTFileList) {
            	LOG.info("FileName:::" + entry.getName());
            	LOG.info("MediaType:::" + entry.getMediaType());
            	LOG.info("SourceUrl:::" + entry.getSourceUrl());
            	LOG.info("LOG::entry::::"+ entry);
            	nft.addFile(NFTFile.create()
            			.name(entry.getName())
            			.mediaType(entry.getMediaType())
            			.src(entry.getSourceUrl())
            	);
            }
        } catch (Exception e) { 
            e.printStackTrace();
        }
        var version = this.MxNFT.getVersion().toString();
		NFTMetadata nftMetadata = NFTMetadata.create()
				.version(version)
                .addNFT(policy.getPolicyId(), nft);

        Tx tx = new Tx()
                .mintAssets(policy.getPolicyScript(), asset, sender.baseAddress())
                .attachMetadata(nftMetadata)
                .from(sender.baseAddress());
        QuickTxBuilder quickTxBuilder = new QuickTxBuilder(backendService);
        Result<String> result = quickTxBuilder.compose(tx)
                .withSigner(SignerProviders.signerFrom(sender))
                .withSigner(SignerProviders.signerFrom(policy))
                .complete();

        System.out.println(result);

        if (result.isSuccessful())
            LOG.info("Transaction Id: " + result.getValue());
        else
            LOG.info("Transaction failed: " + result);
        return result.getValue();
	
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Mint_NFT2";
	}

	// BEGIN EXTRA CODE
	private Network selectedNetwork;
    private String blockfrostUrl = Constants.BLOCKFROST_MAINNET_URL;
	private Account sender;
    public static ILogNode LOG = Core.getLogger("LandanoTest - NFT Creation");

    public void setCardanoNetwork(String networkString) {
        if(networkString.equalsIgnoreCase("preprod")) {
			selectedNetwork = Networks.preprod();
			blockfrostUrl = Constants.BLOCKFROST_PREPROD_URL;
		} else if(networkString.equalsIgnoreCase("testnet")) {
			selectedNetwork = Networks.testnet();
			blockfrostUrl = Constants.BLOCKFROST_TESTNET_URL;
		} else if(networkString.equalsIgnoreCase("preview")) {
			blockfrostUrl = Constants.BLOCKFROST_PREVIEW_URL;
			selectedNetwork = Networks.preview();
		} else {
			selectedNetwork = Networks.mainnet();
			blockfrostUrl = Constants.BLOCKFROST_MAINNET_URL;
		}
    }
    
    
    public static NFT generateNFTMetadata(NFT nft, Map<String, Object> properties) {
//        Policy policy = PolicyUtil.createMultiSigScriptAllPolicy(policyName, 1);
        
//        NFT nft = NFT.create().assetName(assetName);
    	LOG.info("NFT Map::::::");
    	LOG.info(nft.getMap());
    	
        
        for (Map.Entry<String, Object> entry : properties.entrySet()) {
            String key = entry.getKey();
            Object value = entry.getValue();
            System.out.println("properties Key::"+ key);
            System.out.println("properties Value::"+ value);
            
            if (key.equals("files")) {
                List<Map<String, String>> files = (List<Map<String, String>>) value;
                for (Map<String, String> file : files) {
                    nft.addFile(NFTFile.create()
                            .name(file.get("name"))
                            .mediaType(file.get("mediaType"))
                            .src(file.get("src")));
                }
            } else if (key.equals("LA_SpatialUnit")) {
            	LOG.info("inside LA_SpatialUnit::::");
            	LOG.info(value);
            	Map<String, Object> spatialUnit = (Map<String, Object>) value;
                
                if (spatialUnit.containsKey("ReferencePoints")) {
                    List<Map<String, Integer>> referencePoints = (List<Map<String, Integer>>) spatialUnit.get("ReferencePoints");
                    spatialUnit.remove("ReferencePoints");
                    nft.property("LA_SpatialUnit", spatialUnit);
                    CBORMetadataList referencePtArray = new CBORMetadataList();
                    for (Map<String, Integer> point : referencePoints) {
                    	CBORMetadataMap referencePt = new CBORMetadataMap();
                    	for (String pointKey : point.keySet()) {
                    		if((Integer)point.get(pointKey) > (Integer)0) {
                    			referencePt.put(pointKey, BigInteger.valueOf(point.get(pointKey)));
                    		} else {                    			
                    			referencePt.putNegative(pointKey, BigInteger.valueOf(point.get(pointKey)));
                    		}
                    	}
                        referencePtArray.add(referencePt);
                    }
                    
                    var map = nft.getMap();
                    var spatialUnitMap = (co.nstant.in.cbor.model.Map) map.get(new UnicodeString("LA_SpatialUnit"));
                    spatialUnitMap.put(new UnicodeString("ReferencePoints"), referencePtArray.getArray());
                } else {
                	nft.property("LA_SpatialUnit", spatialUnit);
                }
            } else {
                nft.property(key, value.toString());
            }
        }
        
        return nft;

//        return NFTMetadata.create().addNFT(policy.getPolicyId(), nft);
    }
    
    public static Map<String, Object> createPropertiesFromJsonString(String jsonString) throws Exception {
    	System.out.println(jsonString);
        ObjectMapper mapper = new ObjectMapper();
        JsonNode rootNode = mapper.readTree(jsonString);
        System.out.println(rootNode);
        
        return convertJsonNodeToMap(rootNode);
    }

    private static Map<String, Object> convertJsonNodeToMap(JsonNode node) {
        Map<String, Object> map = new HashMap<>();
        
        node.fields().forEachRemaining(entry -> {
            String key = entry.getKey();
            JsonNode value = entry.getValue();
            System.out.println("Key:::"+key);
            System.out.println("Value::"+value);
            
            if (value.isObject()) {
                map.put(key, convertJsonNodeToMap(value));
            } else if (value.isArray()) {
                map.put(key, convertJsonNodeToList(value));
            } else if (value.isNumber()) {
                map.put(key, value.numberValue());
            } else if (value.isBoolean()) {
                map.put(key, value.booleanValue());
            } else {
                map.put(key, value.asText());
            }
        });
        
        return map;
    }

    private static List<Object> convertJsonNodeToList(JsonNode node) {
        List<Object> list = new ArrayList<>();
        
        for (JsonNode element : node) {
            if (element.isObject()) {
                list.add(convertJsonNodeToMap(element));
            } else if (element.isArray()) {
                list.add(convertJsonNodeToList(element));
            } else if (element.isNumber()) {
                list.add(element.numberValue());
            } else if (element.isBoolean()) {
                list.add(element.booleanValue());
            } else {
                list.add(element.asText());
            }
        }
        
        return list;
    }
    
    /*
     import com.bloxbean.cardano.client.api.util.PolicyUtil;
import com.bloxbean.cardano.client.cip.cip25.NFT;
import com.bloxbean.cardano.client.cip.cip25.NFTFile;
import com.bloxbean.cardano.client.cip.cip25.NFTMetadata;
import com.bloxbean.cardano.client.transaction.spec.Policy;
import co.nstant.in.cbor.model.UnicodeString;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadataList;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadataMap;

import java.math.BigInteger;
import java.util.List;
import java.util.Map;

public class DynamicNFTMetadataGenerator {

    public static NFTMetadata generateNFTMetadata(String policyName, String assetName, Map<String, Object> properties) {
        Policy policy = PolicyUtil.createMultiSigScriptAllPolicy(policyName, 1);
        
        NFT nft = NFT.create().assetName(assetName);
        
        for (Map.Entry<String, Object> entry : properties.entrySet()) {
            String key = entry.getKey();
            Object value = entry.getValue();
            
            if (key.equals("files")) {
                List<Map<String, String>> files = (List<Map<String, String>>) value;
                for (Map<String, String> file : files) {
                    nft.addFile(NFTFile.create()
                            .name(file.get("name"))
                            .mediaType(file.get("mediaType"))
                            .src(file.get("src")));
                }
            } else if (key.equals("LA_SpatialUnit")) {
                Map<String, Object> spatialUnit = (Map<String, Object>) value;
                nft.property("LA_SpatialUnit", spatialUnit);
                
                if (spatialUnit.containsKey("ReferencePoints")) {
                    List<Map<String, Integer>> referencePoints = (List<Map<String, Integer>>) spatialUnit.get("ReferencePoints");
                    CBORMetadataList referencePtArray = new CBORMetadataList();
                    for (Map<String, Integer> point : referencePoints) {
                        CBORMetadataMap referencePt = new CBORMetadataMap();
                        referencePt.put("lat", BigInteger.valueOf(point.get("lat")));
                        referencePt.putNegative("Integer", BigInteger.valueOf(point.get("Integer")));
                        referencePtArray.add(referencePt);
                    }
                    
                    var map = nft.getMap();
                    var spatialUnitMap = (co.nstant.in.cbor.model.Map) map.get(new UnicodeString("LA_SpatialUnit"));
                    spatialUnitMap.put(new UnicodeString("ReferencePoints"), referencePtArray.getArray());
                }
            } else {
                nft.property(key, value.toString());
            }
        }

        return NFTMetadata.create().addNFT(policy.getPolicyId(), nft);
    }

    public static void main(String[] args) {
        Map<String, Object> properties = Map.of(
            "city", "SpatialUnit ABC1234",
            "name", "SpatialUnit ABC1234",
            "files", List.of(
                Map.of("src", "https://arweave4.net/1IBE9yoqVSJcxZNJACpcCwuJETQB5iXayOq-1JZbIdc",
                       "name", "Landano Arkly Package4",
                       "mediaType", "application/gzip"),
                Map.of("src", "https://wearehere.com/1IBE9yoqVSJcxZNJACpcCwuJETQB5iXayOq-1JZbIdc",
                       "name", "Landano Arkly Package File 2",
                       "mediaType", "application/gzip")
            ),
            "image", "ipfs://someimageurl-2",
            "country", "country",
            "description", "A unique spatial unit representation.",
            "LA_SpatialUnit", Map.of(
                "Area", "400m2",
                "SU_ID", "SU123454",
                "Dimension", "2D",
                "ReferencePoints", List.of(
                    Map.of("lat", 6733731L, "long", -1778703L),
                    Map.of("lat", 7744731L, "long", -2878703L)
                )
            )
        );

        NFTMetadata nftMetadata = generateNFTMetadata("policy-ld-4", "la_spatialunit_nft_id_4", properties);
        System.out.println(nftMetadata.toString());
    }
}
     * 
     * */
    
	// END EXTRA CODE
}
