// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.math.BigInteger;
import java.util.Arrays;
import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.api.helper.FeeCalculationService;
import com.bloxbean.cardano.client.api.helper.TransactionHelperService;
import com.bloxbean.cardano.client.api.helper.model.TransactionResult;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.common.model.Networks;
import com.bloxbean.cardano.client.crypto.KeyGenUtil;
import com.bloxbean.cardano.client.crypto.Keys;
import com.bloxbean.cardano.client.crypto.SecretKey;
import com.bloxbean.cardano.client.crypto.VerificationKey;
import com.bloxbean.cardano.client.exception.CborSerializationException;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadata;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadataMap;
import com.bloxbean.cardano.client.transaction.model.MintTransaction;
import com.bloxbean.cardano.client.transaction.model.TransactionDetailsParams;
import com.bloxbean.cardano.client.transaction.spec.MultiAsset;
import com.bloxbean.cardano.client.transaction.spec.script.ScriptPubkey;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.bloxbean.cardano.client.api.exception.ApiException;
import com.bloxbean.cardano.client.exception.AddressExcepion;
import com.bloxbean.cardano.client.metadata.Metadata;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadataList;
import com.bloxbean.cardano.client.transaction.spec.Asset;
import com.bloxbean.cardano.client.util.JsonUtil;
import com.bloxbean.cardano.client.util.PolicyUtil;
import com.bloxbean.cardano.client.backend.api.*;
import com.bloxbean.cardano.client.transaction.spec.*;
import com.bloxbean.cardano.client.api.ProtocolParamsSupplier;
import com.bloxbean.cardano.client.api.UtxoSupplier;
import com.bloxbean.cardano.client.api.model.Utxo;
import com.bloxbean.cardano.client.backend.model.Block;
import com.bloxbean.cardano.client.backend.model.TransactionContent;
import com.bloxbean.cardano.client.transaction.spec.TransactionOutput;
import com.bloxbean.cardano.client.util.AssetUtil;
import com.bloxbean.cardano.client.util.Tuple;
import com.bloxbean.cardano.client.quicktx.Tx;
import com.bloxbean.cardano.client.api.model.Amount;
import com.bloxbean.cardano.client.cip.cip20.MessageMetadata;
import com.bloxbean.cardano.client.function.helper.SignerProviders;
import com.bloxbean.cardano.client.quicktx.QuickTxBuilder;
import com.bloxbean.cardano.client.transaction.spec.Policy;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import static com.bloxbean.cardano.client.common.CardanoConstants.LOVELACE;

public class JA_NFT_Create extends CustomJavaAction<java.lang.String>
{
	public JA_NFT_Create(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        LOG.info("NFT Creation");
        BaseInitializations();
        String sender1Mnemonic = "kit color frog trick speak employ suit sort bomb goddess jewel primary spoil fade person useless measure manage warfare reduce few scrub beyond era";
        Account sender1 = new Account(Networks.testnet(), sender1Mnemonic);
        String sender1Addr = sender1.baseAddress();

        String sender2Mnemonic = "essence pilot click armor alpha noise mixture soldier able advice multiply inject ticket pride airport uncover honey desert curtain sun true toast valve half";
        Account sender2 = new Account(Networks.testnet(), sender2Mnemonic);
        String sender2Addr = sender2.baseAddress();

        String receiver1Addr = "addr_test1qqwpl7h3g84mhr36wpetk904p7fchx2vst0z696lxk8ujsjyruqwmlsm344gfux3nsj6njyzj3ppvrqtt36cp9xyydzqzumz82";
        String receiver2Addr = "addr_test1qqqvjp4ffcdqg3fmx0k8rwamnn06wp8e575zcv8d0m3tjn2mmexsnkxp7az774522ce4h3qs4tjp9rxjjm46qf339d9sk33rqn";

        try {
            Policy policy = PolicyUtil.createMultiSigScriptAtLeastPolicy("test_policy", 1, 1);
            String assetName = "MyAsset";
            BigInteger qty = BigInteger.valueOf(1);

            Tx tx = new Tx()
                    .mintAssets(policy.getPolicyScript(), new Asset(assetName, qty), sender1.baseAddress())
                    .attachMetadata(MessageMetadata.create().add("Minting tx"))
                    .from(sender1.baseAddress());

            QuickTxBuilder quickTxBuilder = new QuickTxBuilder(backendService);
            Result<String> result = quickTxBuilder.compose(tx)
                    .withSigner(SignerProviders.signerFrom(sender1))
                    .withSigner(SignerProviders.signerFrom(policy))
                    .complete();

            System.out.println(result);
            LOG.info(result);
            waitForTransactionHash(result);
        } catch (Exception e) {
            e.printStackTrace();
            LOG.info("Exception has occured while minting token"+e.getMessage());
        }
        return "NFT Creation";

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_NFT_Create";
	}

	// BEGIN EXTRA CODE
    private String blockfrostProjectId = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
    public static ILogNode LOG = Core.getLogger("LandanoTest - NFT Creation");
    private TransactionService transactionService;
    protected BackendService backendService;
    protected FeeCalculationService feeCalculationService;
    @SuppressWarnings("deprecation")
    protected TransactionHelperService transactionHelperService;
    protected BlockService blockService;
    protected AssetService assetService;
    protected NetworkInfoService networkInfoService;
    protected UtxoService utxoService;
    protected EpochService epochService;
    // protected UtxoTransactionBuilder utxoTransactionBuilder;

    protected UtxoSupplier utxoSupplier;
    protected ProtocolParamsSupplier protocolParamsSupplier;

    protected void checkIfUtxoAvailable(String txHash, String address) {
        Optional<Utxo> utxo = Optional.empty();
        int count = 0;
        while (utxo.isEmpty()) {
            if (count++ >= 20)
                break;
            List<Utxo> utxos = new DefaultUtxoSupplier(backendService.getUtxoService()).getAll(address);
            utxo = utxos.stream().filter(u -> u.getTxHash().equals(txHash))
                    .findFirst();
            System.out.println("Try to get new output... txhash: " + txHash);
            try {
                Thread.sleep(1000);
            } catch (Exception e) {
            }
        }

    }

    public void BaseInitializations() {
        backendService = new BFBackendService(Constants.BLOCKFROST_TESTNET_URL, this.blockfrostProjectId);
        feeCalculationService = backendService.getFeeCalculationService();
        transactionHelperService = backendService.getTransactionHelperService();
        transactionService = backendService.getTransactionService();
        blockService = backendService.getBlockService();
        assetService = backendService.getAssetService();
        networkInfoService = backendService.getNetworkInfoService();
        utxoService = backendService.getUtxoService();
        epochService = backendService.getEpochService();
        // utxoTransactionBuilder = new UtxoTransactionBuilder();
        utxoSupplier = new DefaultUtxoSupplier(utxoService);
        protocolParamsSupplier = new DefaultProtocolParamsSupplier(epochService);
    }

    protected void waitForTransactionHash(Result<String> result) {
        try {
            if (result.isSuccessful()) { // Wait for transaction to be mined
                int count = 0;
                while (count < 180) {
                    Result<TransactionContent> txnResult = transactionService.getTransaction(result.getValue());
                    if (txnResult.isSuccessful()) {
                        System.out.println(JsonUtil.getPrettyJson(txnResult.getValue()));
                        LOG.info(JsonUtil.getPrettyJson(txnResult.getValue()));
                        break;
                    } else {
                        String waitingMsg = "Waiting for transaction to be processed ....";
                        System.out.println(waitingMsg);
                        LOG.info(waitingMsg);
                    }

                    count++;
                    Thread.sleep(2000);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            LOG.info("Exception has occured while wiaiting for transaction to be mined"+e.getMessage());
        }
    }

    protected void waitForTransaction(Result<TransactionResult> result) {
        try {
            if (result.isSuccessful()) { // Wait for transaction to be mined
                int count = 0;
                while (count < 180) {
                    Result<TransactionContent> txnResult = transactionService
                            .getTransaction(result.getValue().getTransactionId());
                    if (txnResult.isSuccessful()) {
                        System.out.println(JsonUtil.getPrettyJson(txnResult.getValue()));
                        break;
                    } else {
                        System.out.println("Waiting for transaction to be processed ....");
                    }

                    count++;
                    Thread.sleep(2000);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Copy utxo content to TransactionOutput
     *
     * @param changeOutput
     * @param utxo
     */
    protected void copyUtxoValuesToChangeOutput(TransactionOutput changeOutput, Utxo utxo) {
        utxo.getAmount().forEach(utxoAmt -> { // For each amt in utxo
            String utxoUnit = utxoAmt.getUnit();
            BigInteger utxoQty = utxoAmt.getQuantity();
            if (utxoUnit.equals(LOVELACE)) {
                BigInteger existingCoin = changeOutput.getValue().getCoin();
                if (existingCoin == null)
                    existingCoin = BigInteger.ZERO;
                changeOutput.getValue().setCoin(existingCoin.add(utxoQty));
            } else {
                Tuple<String, String> policyIdAssetName = AssetUtil.getPolicyIdAndAssetName(utxoUnit);

                // Find if the policy id is available
                Optional<MultiAsset> multiAssetOptional = changeOutput.getValue().getMultiAssets().stream()
                        .filter(ma -> policyIdAssetName._1.equals(ma.getPolicyId())).findFirst();
                if (multiAssetOptional.isPresent()) {
                    Optional<Asset> assetOptional = multiAssetOptional.get().getAssets().stream()
                            .filter(ast -> policyIdAssetName._2.equals(ast.getName()))
                            .findFirst();
                    if (assetOptional.isPresent()) {
                        BigInteger changeVal = assetOptional.get().getValue().add(utxoQty);
                        assetOptional.get().setValue(changeVal);
                    } else {
                        Asset asset = new Asset(policyIdAssetName._2, utxoQty);
                        multiAssetOptional.get().getAssets().add(asset);
                    }
                } else {
                    Asset asset = new Asset(policyIdAssetName._2, utxoQty);
                    MultiAsset multiAsset = new MultiAsset(policyIdAssetName._1, new ArrayList<>(Arrays.asList(asset)));
                    changeOutput.getValue().getMultiAssets().add(multiAsset);
                }
            }
        });

        // Remove any empty MultiAssets
        List<MultiAsset> multiAssets = changeOutput.getValue().getMultiAssets();
        List<MultiAsset> markedForRemoval = new ArrayList<>();
        if (multiAssets != null && multiAssets.size() > 0) {
            multiAssets.forEach(ma -> {
                if (ma.getAssets() == null || ma.getAssets().size() == 0)
                    markedForRemoval.add(ma);
            });

            if (markedForRemoval != null && !markedForRemoval.isEmpty())
                multiAssets.removeAll(markedForRemoval);
        }
    }
    /*
     * public java.lang.String createNewToken(String ipfshHash) throws
     * CborSerializationException, ApiException, AddressExcepion {
     * LOG.info("Creating NFT" + ipfshHash);
     * // return "JA_NFT_Create";
     * String mnemonics =
     * "wealth tattoo weapon conduct picture grain exclude arch match install movie drift bid poverty judge anchor patch dismiss chalk film during gasp work hedgehog"
     * ;
     * Account sender = new Account(Networks.preprod(), mnemonics);
     * BFBackendService backendService = new
     * BFBackendService(Constants.BLOCKFROST_PREPROD_URL,
     * blockfrostProjectId);
     * // Get the necessary Blockfrost Services
     * BlockService blockService = backendService.getBlockService();
     * FeeCalculationService feeCalculationService =
     * backendService.getFeeCalculationService();
     * transactionService = backendService.getTransactionService();
     * 
     * @SuppressWarnings("deprecation")
     * TransactionHelperService transactionHelperService =
     * backendService.getTransactionHelperService();
     * 
     * Keys keys = null;
     * VerificationKey vkey= null;
     * SecretKey skey = null;
     * try {
     * keys = KeyGenUtil.generateKey();
     * vkey = keys.getVkey();
     * skey = keys.getSkey();
     * } catch (CborSerializationException e) {
     * // e.printStackTrace();
     * LOG.info("Failed to get policy ID", e);
     * throw new RuntimeException("Failed to get policy ID", e);
     * }
     * 
     * 
     * /*Keys keys = KeyGenUtil.generateKey();
     * VerificationKey verificationKey = keys.getVkey();
     * SecretKey secretKey = keys.getSkey();
     * String paymentSigningKeyCborHex = secretKey.getCborHex();
     * LOG.info("Payment Signing Key CBOR Hex:: "+paymentSigningKeyCborHex);
     */

    /*
     * ScriptPubkey scriptPubkey = ScriptPubkey.create(vkey);
     * // This is the policy ID of the NFT
     * String policyId;
     * // try {
     * policyId = scriptPubkey.getPolicyId();
     * // } catch (CborSerializationException e) {
     * LOG.info("Failed to get policy ID");
     * // throw new RuntimeException("Failed to get policy ID", e);
     * // }
     * 
     * 
     * MultiAsset multiAsset = new MultiAsset();
     * multiAsset.setPolicyId(policyId);
     * // Set here the name of the Asset and how many to mint
     * // In our case, we only want 1
     * com.bloxbean.cardano.client.transaction.spec.Asset asset = new
     * com.bloxbean.cardano.client.transaction.spec.Asset(
     * "ChristLove", BigInteger.valueOf(1));
     * multiAsset.getAssets().add(asset);
     * // Create the metadata. Follow the standard defined here
     * // https://cips.cardano.org/cips/cip25/
     * CBORMetadataMap nftInfo = new CBORMetadataMap()
     * .put("image", "ChristLove")
     * .put("name", "ChristLove")
     * .put("etc", "Greater love has a no, than a man should lay down his life.");
     * CBORMetadataMap nameMetadata = new CBORMetadataMap()
     * .put("ChristLove", nftInfo);
     * CBORMetadataMap policyMetadata = new CBORMetadataMap()
     * .put(policyId, nameMetadata);
     * CBORMetadata metadata = new CBORMetadata()
     * .put(new BigInteger("721"), policyMetadata);
     * 
     * MintTransaction mintTransaction = MintTransaction.builder()
     * .sender(sender)
     * .mintAssets(Arrays.asList(multiAsset))
     * .policyScript(scriptPubkey)
     * .policyKeys(Arrays.asList(skey))
     * .build();
     * long ttl = blockService.getLatestBlock().getValue().getSlot() + 1000;
     * TransactionDetailsParams detailsParams = TransactionDetailsParams.builder()
     * .ttl(ttl)
     * .build();
     * BigInteger fee = feeCalculationService.calculateFee(mintTransaction,
     * detailsParams, metadata);
     * System.out.println(fee.longValue());
     * mintTransaction.setFee(fee);
     * 
     * Result<TransactionResult> result =
     * transactionHelperService.mintToken(mintTransaction, detailsParams,
     * metadata);
     * String resultString = "";
     * if (result.isSuccessful()) {
     * resultString = "Transaction ID: " + result.getValue().getTransactionId();
     * LOG.info(resultString);
     * } else {
     * resultString = "Transaction Failed: " + result;
     * LOG.info(resultString);
     * }
     * 
     * return resultString;
     * }
     */

    /*
     * public void mintToken() throws CborSerializationException, ApiException,
     * AddressExcepion {
     * Keys keys = KeyGenUtil.generateKey();
     * VerificationKey vkey = keys.getVkey();
     * SecretKey skey = keys.getSkey();
     * 
     * ScriptPubkey scriptPubkey = ScriptPubkey.create(vkey);
     * String policyId = scriptPubkey.getPolicyId();
     * 
     * String senderMnemonic =
     * "kit color frog trick speak employ suit sort bomb goddess jewel primary spoil fade person useless measure manage warfare reduce few scrub beyond era"
     * ;
     * Account sender = new Account(Networks.testnet(), senderMnemonic);
     * // String receiver =
     * "addr_test1qqwpl7h3g84mhr36wpetk904p7fchx2vst0z696lxk8ujsjyruqwmlsm344gfux3nsj6njyzj3ppvrqtt36cp9xyydzqzumz82";
     * 
     * MultiAsset multiAsset = new MultiAsset();
     * multiAsset.setPolicyId(policyId);
     * Asset asset = new Asset("TestCoin", BigInteger.valueOf(250000));
     * multiAsset.getAssets().add(asset);
     * 
     * //Metadata
     * CBORMetadataMap tokenInfoMap
     * = new CBORMetadataMap()
     * .put("token", "Test Token")
     * .put("symbol", "TTOK");
     * 
     * CBORMetadataList tagList
     * = new CBORMetadataList()
     * .add("tag1")
     * .add("tag2");
     * 
     * Metadata metadata = new CBORMetadata()
     * .put(new BigInteger("670001"), tokenInfoMap)
     * .put(new BigInteger("670002"), tagList);
     * 
     * MintTransaction paymentTransaction =
     * MintTransaction.builder()
     * .sender(sender)
     * .receiver(sender.baseAddress())
     * .mintAssets(Arrays.asList(multiAsset))
     * .policyScript(scriptPubkey)
     * .policyKeys(Arrays.asList(skey))
     * .build();
     * 
     * TransactionDetailsParams detailsParams =
     * TransactionDetailsParams.builder().ttl(getTtl()).build();
     * 
     * BigInteger fee = feeCalculationService.calculateFee(paymentTransaction,
     * detailsParams, metadata);
     * paymentTransaction.setFee(fee);
     * 
     * Result<TransactionResult> result =
     * transactionHelperService.mintToken(paymentTransaction, detailsParams,
     * metadata);
     * System.out.println(result);
     * 
     * System.out.println("Request: \n" +
     * JsonUtil.getPrettyJson(paymentTransaction));
     * if (result.isSuccessful())
     * System.out.println("Transaction Id: " + result.getValue());
     * else
     * System.out.println("Transaction failed: " + result);
     * 
     * waitForTransaction(result);
     * }
     */

    /*
     * public void waitForTransaction(Result<String> result) {
     * try {
     * if (result.isSuccessful()) { // Wait for transaction to be mined
     * int count = 0;
     * while (count < 180) {
     * Result<TransactionContent> txnResult =
     * transactionService.getTransaction(result.getValue().getTr);
     * if (txnResult.isSuccessful()) {
     * System.out.println(JsonUtil.getPrettyJson(txnResult.getValue()));
     * break;
     * } else {
     * System.out.println("Waiting for transaction to be mined ....");
     * }
     * count++;
     * Thread.sleep(2000);
     * }
     * }
     * } catch (Exception e) {
     * e.printStackTrace();
     * }
     * }
     */

	// END EXTRA CODE
}
