// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import cardanowallet.Utils;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.bloxbean.cardano.client.address.AddressProvider;
import com.bloxbean.cardano.client.transaction.spec.Policy;
import com.bloxbean.cardano.client.transaction.spec.script.NativeScript;
import com.bloxbean.cardano.client.transaction.util.NativeScriptDeserializer;
import com.bloxbean.cardano.client.util.HexUtil;

public class JA_PolicyScript_Create extends CustomJavaAction<java.lang.Void>
{
	/** @deprecated use Policy.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Policy;
	private final cardanowallet.proxies.Policy Policy;

	public JA_PolicyScript_Create(
		IContext context,
		IMendixObject _policy
	)
	{
		super(context);
		this.__Policy = _policy;
		this.Policy = _policy == null ? null : cardanowallet.proxies.Policy.initialize(getContext(), _policy);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		var utils = new Utils(this.Policy.getCardanonetwork().toString().toLowerCase());
		NativeScript nativeScript = NativeScript.deserializeJson(this.Policy.getScriptJSON());
        byte[] serializedBytes = nativeScript.serializeScriptBody();
        String hexRepresentation = HexUtil.encodeHexString(serializedBytes);
		this.Policy.setScriptHash(hexRepresentation);
	    String nativeScriptBech32Address = AddressProvider.getEntAddress(nativeScript, utils.getCardanoNetwork()).toBech32();
	    this.Policy.setAddress(nativeScriptBech32Address);
		Policy policy = new Policy(this.Policy.getName(), nativeScript);
		this.Policy.setPolicyId(policy.getPolicyId());
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_PolicyScript_Create";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
