// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.util.Base64;
import java.util.List;
import java.util.Optional;
import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.address.Address;
import com.bloxbean.cardano.client.address.AddressProvider;
import com.bloxbean.cardano.client.api.UtxoSupplier;
import com.bloxbean.cardano.client.api.exception.ApiException;
import com.bloxbean.cardano.client.api.model.Amount;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.api.model.Utxo;
import com.bloxbean.cardano.client.backend.api.BackendService;
import com.bloxbean.cardano.client.backend.api.DefaultUtxoSupplier;
import com.bloxbean.cardano.client.backend.api.TransactionService;
import com.bloxbean.cardano.client.backend.api.UtxoService;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.backend.model.TransactionContent;
import com.bloxbean.cardano.client.common.model.Network;
import com.bloxbean.cardano.client.common.model.Networks;
import com.bloxbean.cardano.client.crypto.SecretKey;
import com.bloxbean.cardano.client.exception.CborSerializationException;
import com.bloxbean.cardano.client.function.helper.ScriptUtxoFinders;
import com.bloxbean.cardano.client.function.helper.SignerProviders;
import com.bloxbean.cardano.client.plutus.blueprint.PlutusBlueprintUtil;
import com.bloxbean.cardano.client.plutus.blueprint.model.PlutusVersion;
import com.bloxbean.cardano.client.plutus.spec.BytesPlutusData;
import com.bloxbean.cardano.client.plutus.spec.ConstrPlutusData;
import com.bloxbean.cardano.client.plutus.spec.PlutusData;
import com.bloxbean.cardano.client.plutus.spec.PlutusScript;
import com.bloxbean.cardano.client.quicktx.QuickTxBuilder;
import com.bloxbean.cardano.client.quicktx.ScriptTx;
import com.bloxbean.cardano.client.quicktx.Tx;
import com.bloxbean.cardano.client.util.JsonUtil;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import cardanowallet.EncryptDecryptMnemonic;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_SmartContract_Unlock extends CustomJavaAction<IMendixObject>
{
	private final java.lang.String PlutusScriptCode;
	private final java.lang.String ReceiverAddress;
	private final cardanowallet.proxies.Enum_CardanoNetwork CardanoNetwork;
	private final java.lang.String RedeemerGuess;
	/** @deprecated use ContractScript.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ContractScript;
	private final cardanowallet.proxies.Script ContractScript;
	private final java.math.BigDecimal ContractAmount;
	/** @deprecated use SenderWallet.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __SenderWallet;
	private final cardanowallet.proxies.Wallet SenderWallet;

	public JA_SmartContract_Unlock(
		IContext context,
		java.lang.String _plutusScriptCode,
		java.lang.String _receiverAddress,
		java.lang.String _cardanoNetwork,
		java.lang.String _redeemerGuess,
		IMendixObject _contractScript,
		java.math.BigDecimal _contractAmount,
		IMendixObject _senderWallet
	)
	{
		super(context);
		this.PlutusScriptCode = _plutusScriptCode;
		this.ReceiverAddress = _receiverAddress;
		this.CardanoNetwork = _cardanoNetwork == null ? null : cardanowallet.proxies.Enum_CardanoNetwork.valueOf(_cardanoNetwork);
		this.RedeemerGuess = _redeemerGuess;
		this.__ContractScript = _contractScript;
		this.ContractScript = _contractScript == null ? null : cardanowallet.proxies.Script.initialize(getContext(), _contractScript);
		this.ContractAmount = _contractAmount;
		this.__SenderWallet = _senderWallet;
		this.SenderWallet = _senderWallet == null ? null : cardanowallet.proxies.Wallet.initialize(getContext(), _senderWallet);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		blockfrostProjectID = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
		receiver = this.ReceiverAddress;
		compiledCode = this.PlutusScriptCode;
		assignBlockfrostNetwork(CardanoNetwork.name());
		backendService = new BFBackendService(blockfrostUrl, blockfrostProjectID);
		transactionService = backendService.getTransactionService();
		
		this.unlock();
		return this.ContractScript.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_SmartContract_Unlock";
	}

	// BEGIN EXTRA CODE
	public static ILogNode LOG = Core.getLogger("LandanoTest");
	private Network selectedNetwork;
	private String blockfrostUrl;
	private String blockfrostProjectID = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
	
	private Account sender;
	private String receiver; // = this.ReceiverAddress;// "addr_test1qq5zpspqs6m7mzxq808avasa5tseuhewvcv46px7ap8afzz28vgl6r803aayrz2lapzgevpyy55sj27gc0ncwhkqydlq5m0v5k";
	private String compiledCode; // = this.PlutusScriptCode; //"59019401010032323232323232323225333003323232323253330083370e900118051baa001132323253333330120051533300b3370e900018069baa005132533301000100b132533333301400100c00c00c00c132533301230140031533300e3370e900018081baa004132533300f3371e6eb8c050c048dd5004a450d48656c6c6f2c20576f726c642100100114a06644646600200200644a66602c00229404c94ccc04ccdc79bae301800200414a226600600600260300026eb0c04cc050c050c050c050c050c050c050c050c044dd50051bae301330113754602660226ea801054cc03d24012465787065637420536f6d6528446174756d207b206f776e6572207d29203d20646174756d001600d375c0026022002601c6ea8014028028028028028c03cc040008c038004c02cdd50008b1806180680118058009805801180480098031baa001149854cc0112411856616c696461746f722072657475726e65642066616c73650013656153300249011272656465656d65723a2052656465656d657200165734ae7155ceaab9e5573eae855d12ba41";
	    //Blockfrost
	private BackendService backendService; // = new BFBackendService(blockfrostUrl, blockfrostProjectID);
	private TransactionService transactionService;
	
	private PlutusScript plutusScript; // = PlutusBlueprintUtil.getPlutusScriptFromCompiledCode(compiledCode, PlutusVersion.v3);
	private String scriptAddr; // = AddressProvider.getEntAddress(plutusScript, Networks.testnet()).toBech32();

    public String unlock() throws ApiException {
    	var resultString = "";
    	try {
    	plutusScript = PlutusBlueprintUtil.getPlutusScriptFromCompiledCode(this.ContractScript.getPlutusScriptCode(), PlutusVersion.v3);
    	scriptAddr = this.ContractScript.getScriptAddress();
    	String senderBaseAddress = this.ContractScript.getSenderAddress();
    	Address senderAddress = new Address(senderBaseAddress);
    	receiver = this.ReceiverAddress;
    	
        Utxo scriptUtxo = getAvailableUtxo(backendService.getUtxoService(), this.ContractScript.getLockTransactionHash(), scriptAddr).orElseThrow();

        PlutusData redeemer = ConstrPlutusData.of(0, BytesPlutusData.of(this.RedeemerGuess));

        ScriptTx scriptTx = new ScriptTx()
                .collectFrom(scriptUtxo, redeemer)
                .payToAddress(receiver, Amount.ada(this.ContractAmount.doubleValue()))
                .attachSpendingValidator(plutusScript);
        

        QuickTxBuilder quickTxBuilder = new QuickTxBuilder(backendService);
        Result<String> result;
		LOG.info("Createing result object\n==========");
			result = quickTxBuilder.compose(scriptTx)
			        .feePayer(receiver)
			        .collateralPayer(senderBaseAddress)
			        .withSigner(SignerProviders.signerFrom(SecretKey.create(
			        		Base64.getDecoder().decode(this.SenderWallet.getSKey()))))
			        .withRequiredSigners(senderAddress)
			        .completeAndWait(System.out::println);
			
			/*var ddd = new EncryptDecryptMnemonic();
			var sender = new Account(selectedNetwork, ddd.decrypt(this.SenderWallet.getMnemonicEncrypted(), this.SenderPassPhrase));
			result = quickTxBuilder.compose(scriptTx)
		        .feePayer(receiver)
		        .collateralPayer(senderBaseAddress)
		        .withSigner(SignerProviders.signerFrom(sender))
		        .withRequiredSigners(senderAddress)
		        .completeAndWait(System.out::println);*/
	        
			System.out.println(result);
			LOG.info(result);
	        return result.toString();
			
		} catch (CborSerializationException e) {
			// TODO Auto-generated catch block
			LOG.error(e);
//			return e.toString();
		} catch (Exception e) {
			// TODO Auto-generated catch block4
			 e.printStackTrace();
			 System.out.println(e);
			 LOG.error(e);
		}
    	return resultString;
//		return PlutusScriptCode;

    }
 	
    

	private void assignBlockfrostNetwork(String networkString) {
		if(networkString.equalsIgnoreCase("preprod")) {
			selectedNetwork = Networks.preprod();
			blockfrostUrl = Constants.BLOCKFROST_PREPROD_URL;
		} else if(networkString.equalsIgnoreCase("testnet")) {
			selectedNetwork = Networks.testnet();
			blockfrostUrl = Constants.BLOCKFROST_TESTNET_URL;
		} else if(networkString.equalsIgnoreCase("preview")) {
			blockfrostUrl = Constants.BLOCKFROST_PREVIEW_URL;
			selectedNetwork = Networks.preview();
		} else {
			selectedNetwork = Networks.mainnet();
			blockfrostUrl = Constants.BLOCKFROST_MAINNET_URL;
		}
	}
    
	public void waitForTransaction(Result<String> result) {
		try {
			if (result.isSuccessful()) { //Wait for transaction to be mined
				int count = 0;
				while (count < 60) {
					Result<TransactionContent> txnResult = transactionService.getTransaction(result.getValue());
					if (txnResult.isSuccessful()) {
						System.out.println(JsonUtil.getPrettyJson(txnResult.getValue()));
						break;
					} else {
						System.out.println("Waiting for transaction to be mined ....");
					}
					count++;
					Thread.sleep(2000);
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	private Optional<Utxo> getAvailableUtxo (UtxoService utxoService, String txHash, String address) {
		Optional<Utxo> utxo = Optional.empty();
        int count = 0;
        while (utxo.isEmpty()) {
            if (count++ >= 20)
                break;
            List<Utxo> utxos = new DefaultUtxoSupplier(utxoService).getAll(address);
            utxo = utxos.stream().filter(u -> u.getTxHash().equals(txHash))
                    .findFirst();
            if(utxo.isPresent()) {
                System.out.println("Output got is::::"+String.valueOf(count) +" :::::::: " + utxo.get().toString());
            }
            System.out.println("Try to get new output... txhash: " + txHash);

            try {
                Thread.sleep(1000);
            } catch (Exception e) {}
        }
        return utxo;
    }
	
	
	// END EXTRA CODE
}
