// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.api.ProtocolParamsSupplier;
import com.bloxbean.cardano.client.api.UtxoSupplier;
import com.bloxbean.cardano.client.api.exception.ApiException;
import com.bloxbean.cardano.client.backend.api.BackendService;
import com.bloxbean.cardano.client.backend.api.DefaultProtocolParamsSupplier;
import com.bloxbean.cardano.client.backend.api.DefaultUtxoSupplier;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.common.model.Networks;
import java.math.BigInteger;
import java.util.Optional;
import com.bloxbean.cardano.client.address.AddressProvider;
import com.bloxbean.cardano.client.api.model.Amount;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.api.model.Utxo;
import com.bloxbean.cardano.client.common.CardanoConstants;
import com.bloxbean.cardano.client.function.helper.ScriptUtxoFinders;
import com.bloxbean.cardano.client.function.helper.SignerProviders;
import com.bloxbean.cardano.client.plutus.blueprint.PlutusBlueprintUtil;
import com.bloxbean.cardano.client.plutus.blueprint.model.PlutusVersion;
import com.bloxbean.cardano.client.plutus.spec.BigIntPlutusData;
import com.bloxbean.cardano.client.plutus.spec.BytesPlutusData;
import com.bloxbean.cardano.client.plutus.spec.ConstrPlutusData;
import com.bloxbean.cardano.client.plutus.spec.PlutusData;
import com.bloxbean.cardano.client.plutus.spec.PlutusScript;
import com.bloxbean.cardano.client.plutus.spec.PlutusV2Script;
import com.bloxbean.cardano.client.quicktx.QuickTxBuilder;
import com.bloxbean.cardano.client.quicktx.ScriptTx;
import com.bloxbean.cardano.client.quicktx.Tx;
import com.bloxbean.cardano.client.transaction.spec.TransactionInput;
import com.bloxbean.cardano.client.util.JsonUtil;

public class JA_SmartContractHello extends CustomJavaAction<java.lang.String>
{
	public JA_SmartContractHello(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String lock = this.lock();
		String unlock = this.unlock();
		String smartContract = lock +"\n\n==============\n\n"+unlock;
		return smartContract;
//		return this.lock();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_SmartContractHello";
	}

	// BEGIN EXTRA CODE
	
     private String senderMnemonic = "wealth tattoo weapon conduct picture grain exclude arch match install movie drift bid poverty judge anchor patch dismiss chalk film during gasp work hedgehog";
	 private   Account sender = new Account(Networks.preprod(), senderMnemonic);
	 private   String receiver = "addr_test1qq5zpspqs6m7mzxq808avasa5tseuhewvcv46px7ap8afzz28vgl6r803aayrz2lapzgevpyy55sj27gc0ncwhkqydlq5m0v5k";
	 private String compiledCode ="59019401010032323232323232323225333003323232323253330083370e900118051baa001132323253333330120051533300b3370e900018069baa005132533301000100b132533333301400100c00c00c00c132533301230140031533300e3370e900018081baa004132533300f3371e6eb8c050c048dd5004a450d48656c6c6f2c20576f726c642100100114a06644646600200200644a66602c00229404c94ccc04ccdc79bae301800200414a226600600600260300026eb0c04cc050c050c050c050c050c050c050c050c044dd50051bae301330113754602660226ea801054cc03d24012465787065637420536f6d6528446174756d207b206f776e6572207d29203d20646174756d001600d375c0026022002601c6ea8014028028028028028c03cc040008c038004c02cdd50008b1806180680118058009805801180480098031baa001149854cc0112411856616c696461746f722072657475726e65642066616c73650013656153300249011272656465656d65723a2052656465656d657200165734ae7155ceaab9e5573eae855d12ba41";
//	 private    String compiledCode = "590169010100323232323232323225333002323232323253330073370e900118049baa0011323232533300a3370e900018061baa005132533300f00116132533333301300116161616132533301130130031533300d3370e900018079baa004132533300e3371e6eb8c04cc044dd5004a4410d48656c6c6f2c20576f726c642100100114a06644646600200200644a66602a00229404c94ccc048cdc79bae301700200414a2266006006002602e0026eb0c048c04cc04cc04cc04cc04cc04cc04cc04cc040dd50051bae301230103754602460206ea801054cc03924012465787065637420536f6d6528446174756d207b206f776e6572207d29203d20646174756d001616375c0026020002601a6ea801458c038c03c008c034004c028dd50008b1805980600118050009805001180400098029baa001149854cc00d2411856616c696461746f722072657475726e65642066616c736500136565734ae7155ceaab9e5573eae855d12ba401";

	    //For Yaci DevKit (https://devkit.yaci.xyz/)
//	 private    BackendService backendService = new BFBackendService("http://localhost:8080/api/v1/", "dummy_key");

	    //Blockfrost
	 private    BackendService backendService = new BFBackendService(Constants.BLOCKFROST_PREPROD_URL, "preprodoqh304gIgYVyyNtpiv3TkpMsBQttuHzr");

	 private PlutusScript plutusScript = PlutusBlueprintUtil.getPlutusScriptFromCompiledCode(compiledCode, PlutusVersion.v3);
	 private String scriptAddr = AddressProvider.getEntAddress(plutusScript, Networks.testnet()).toBech32();

	    public String lock() {
	        //create datum
	        PlutusData datum = ConstrPlutusData.of(0, BytesPlutusData.of(sender.getBaseAddress().getPaymentCredentialHash().get()));

	        Tx tx = new Tx()
	                .payToContract(scriptAddr, Amount.ada(4), datum)
	                .from(sender.baseAddress());

	        QuickTxBuilder quickTxBuilder = new QuickTxBuilder(backendService);
	        Result<String> result = quickTxBuilder.compose(tx)
	                .withSigner(SignerProviders.signerFrom(sender))
	                .completeAndWait(System.out::println);

	        System.out.println(result);
	        return result.toString();
	    }

	    public String unlock() throws ApiException {
	        PlutusData datum = ConstrPlutusData.of(0, BytesPlutusData.of(sender.getBaseAddress().getPaymentCredentialHash().get()));

	        UtxoSupplier utxoSupplier = new DefaultUtxoSupplier(backendService.getUtxoService());
	        Utxo scriptUtxo = ScriptUtxoFinders.findFirstByInlineDatum(utxoSupplier, scriptAddr, datum).orElseThrow();

	        PlutusData redeemer = ConstrPlutusData.of(0, BytesPlutusData.of("Hello, World!"));

	        ScriptTx scriptTx = new ScriptTx()
	                .collectFrom(scriptUtxo, redeemer)
	                .payToAddress(receiver, Amount.ada(4))
	                .attachSpendingValidator(plutusScript);

	        QuickTxBuilder quickTxBuilder = new QuickTxBuilder(backendService);
	        Result<String> result = quickTxBuilder.compose(scriptTx)
	                .feePayer(receiver)
	                .collateralPayer(sender.baseAddress())
	                .withSigner(SignerProviders.signerFrom(sender))
	                .withRequiredSigners(sender.getBaseAddress())
	                .completeAndWait(System.out::println);

	        System.out.println(result);
	        return result.toString();
	    }
	
	// END EXTRA CODE
}
