// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.nio.charset.StandardCharsets;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JA_StringToHex extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String StringToHex;

	public JA_StringToHex(
		IContext context,
		java.lang.String _stringToHex
	)
	{
		super(context);
		this.StringToHex = _stringToHex;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuilder hexString = new StringBuilder();
	    for (char ch : StringToHex.toCharArray()) {
	        hexString.append(String.format("%02x", (int) ch));
	    }
	    return hexString.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_StringToHex";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
