// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.util.ArrayList;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.common.cbor.CborSerializationUtil;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.bloxbean.cardano.client.transaction.spec.TransactionWitnessSet;
import com.bloxbean.cardano.client.util.HexUtil;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import cardanowallet.Utils;
import co.nstant.in.cbor.model.DataItem;
import co.nstant.in.cbor.model.Map;

public class JA_Transaction_Submit extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String TransactionCBOR;
	private final java.lang.String WitnessCBOR;
	private final cardanowallet.proxies.Enum_CardanoNetwork CardanoNetwork;

	public JA_Transaction_Submit(
		IContext context,
		java.lang.String _transactionCBOR,
		java.lang.String _witnessCBOR,
		java.lang.String _cardanoNetwork
	)
	{
		super(context);
		this.TransactionCBOR = _transactionCBOR;
		this.WitnessCBOR = _witnessCBOR;
		this.CardanoNetwork = _cardanoNetwork == null ? null : cardanowallet.proxies.Enum_CardanoNetwork.valueOf(_cardanoNetwork);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		var utils = new Utils(this.CardanoNetwork.getCaption());
	    // 1. Deserialize original transaction
        Transaction transaction = Transaction.deserialize(HexUtil.decodeHexString(TransactionCBOR));

        // 2. Deserialize witness set from CIP-30
        DataItem witnessDI = CborSerializationUtil.deserialize(HexUtil.decodeHexString(WitnessCBOR));
        //TransactionWitnessSet walletWitnessSet = TransactionWitnessSet.deserialize((Map) witnessDI);
        TransactionWitnessSet walletWitnessSet = TransactionWitnessSet.deserialize((Map) witnessDI);

        // 3. Merge wallet witness into original transaction
        if (transaction.getWitnessSet() == null) {
            transaction.setWitnessSet(new TransactionWitnessSet());
        }

        if (transaction.getWitnessSet().getVkeyWitnesses() == null)
            transaction.getWitnessSet().setVkeyWitnesses(new ArrayList<>());

        transaction.getWitnessSet().getVkeyWitnesses().addAll(walletWitnessSet.getVkeyWitnesses());

        // 4. Submit transaction
        Result<String> result = utils.backendService.getTransactionService().submitTransaction(transaction.serialize());

        if (result.isSuccessful()) {
            return result.getValue(); // Transaction hash
        } else {
            throw new RuntimeException("Transaction submission failed: " + result.getResponse());
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Transaction_Submit";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
