// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class ParseDateTimeToCardanoSlot extends CustomJavaAction<java.lang.Long>
{
	private final cardanowallet.proxies.Enum_CardanoNetwork Network;
	private final java.util.Date InputDate;

	public ParseDateTimeToCardanoSlot(
		IContext context,
		java.lang.String _network,
		java.util.Date _inputDate
	)
	{
		super(context);
		this.Network = _network == null ? null : cardanowallet.proxies.Enum_CardanoNetwork.valueOf(_network);
		this.InputDate = _inputDate;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (InputDate == null) {
            throw new IllegalArgumentException("Date/Time input cannot be null");
        }

        // Convert java.util.Date to Unix Time (seconds)
        long inputUnixTime = InputDate.getTime() / 1000;

        // Shelley Hard Fork Timestamp (Unix time in seconds)
        long shelleyHardForkTime;
        
        switch (this.Network) {
            case Mainnet:
                shelleyHardForkTime = 1654041600L;
                break;
            case Preview:
                shelleyHardForkTime = 1666656000L;
                break;
            case Preprod:
                shelleyHardForkTime = 1654041600L;
                break;
            default:
                throw new IllegalArgumentException("Unsupported network: " + Network);
        }

        // Ensure the given date is after Shelley hard fork
        if (inputUnixTime < shelleyHardForkTime) {
            throw new IllegalArgumentException("Date must be after Shelley hard fork (July 29, 2020)");
        }

        // Calculate slot number (1 second per slot)
        return inputUnixTime - shelleyHardForkTime;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ParseDateTimeToCardanoSlot";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
